import { Question } from '../../types';

export const MODULE_2_QUESTIONS: Question[] = [
  {
    id: 'q_161',
    topicId: 'top_re_intro',
    text: `What is the primary purpose of a Regular Expression?`,
    correctAnswer: `To declaratively describe a language using algebraic operations`,
    options: [`To declaratively describe a language using algebraic operations`, `To physically process strings with finite memory`, `To define context-free grammars`, `To simulate a Turing Machine`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Regular Expressions are declarative. They specify what the patterns are, rather than the state transitions used to parse them.`,
    keyConcept: `Definition of RE`,
    commonMistake: ``
  },
  {
    id: 'q_162',
    topicId: 'top_re_intro',
    text: `Which of the following is NOT a fundamental base case in the recursive definition of Regular Expressions?`,
    correctAnswer: `Any string of length greater than one`,
    options: [`Any string of length greater than one`, `The empty set ∅`, `The empty string ε`, `A single symbol from the alphabet Σ`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The base cases are ∅, ε, and single symbols a ∈ Σ. Longer strings are formed by concatenation.`,
    keyConcept: `Recursive definition of RE`,
    commonMistake: ``
  },
  {
    id: 'q_163',
    topicId: 'top_re_intro',
    text: `Which algebraic operator is NOT part of the standard regular expression definition?`,
    correctAnswer: `Intersection`,
    options: [`Intersection`, `Union (+)`, `Concatenation`, `Kleene Star (*)`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Standard Regular Expressions only use Union, Concatenation, and Kleene Star.`,
    keyConcept: `RE operations`,
    commonMistake: ``
  },
  {
    id: 'q_164',
    topicId: 'top_re_intro',
    text: `What is the language denoted by the regular expression ∅?`,
    correctAnswer: `The empty language {}`,
    options: [`The empty language {}`, `The language containing the empty string {ε}`, `The set of all strings Σ*`, `Undefined`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `∅ denotes a language with no strings. ε denotes a language with one string of length zero.`,
    keyConcept: `∅ vs ε`,
    commonMistake: ``
  },
  {
    id: 'q_165',
    topicId: 'top_re_intro',
    text: `What is the language denoted by the regular expression ε?`,
    correctAnswer: `{ε}`,
    options: [`{ε}`, `{}`, `Σ*`, `{∅}`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `ε represents the language containing exactly one string: the empty string.`,
    keyConcept: `∅ vs ε`,
    commonMistake: ``
  },
  {
    id: 'q_166',
    topicId: 'top_re_intro',
    text: `If R is a regular expression, what does L(R) represent?`,
    correctAnswer: `The language described by R`,
    options: [`The language described by R`, `The length of R`, `The Kleene closure of R`, `The reverse of R`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `L(R) is the standard notation for the language defined by the regular expression R.`,
    keyConcept: `Notation`,
    commonMistake: ``
  },
  {
    id: 'q_167',
    topicId: 'top_re_intro',
    text: `Which of the following is an RE for the language over {0,1} containing only the exact string '01'?`,
    correctAnswer: `01`,
    options: [`01`, `0+1`, `0*1*`, `(01)*`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Concatenation of '0' and '1' yields exactly the string '01'.`,
    keyConcept: `Concatenation`,
    commonMistake: ``
  },
  {
    id: 'q_168',
    topicId: 'top_re_intro',
    text: `How does the Kleene Star (*) operator function in a regular expression?`,
    correctAnswer: `It allows zero or more repetitions of the preceding element`,
    options: [`It allows zero or more repetitions of the preceding element`, `It requires exactly one repetition`, `It requires one or more repetitions`, `It allows zero repetitions only`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `R* means repeating R 0, 1, 2, or infinite times.`,
    keyConcept: `Kleene Star`,
    commonMistake: ``
  },
  {
    id: 'q_169',
    topicId: 'top_re_intro',
    text: `If r = a and s = b are REs, what does the RE (r + s) denote?`,
    correctAnswer: `{a, b}`,
    options: [`{a, b}`, `{ab}`, `{a, b}*`, `{ab, ba}`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The union operator (+) combines the strings from both languages.`,
    keyConcept: `Union`,
    commonMistake: ``
  },
  {
    id: 'q_170',
    topicId: 'top_re_intro',
    text: `What is the difference between R* and R^+ in standard notation?`,
    correctAnswer: `R* includes zero repetitions (ε), while R^+ requires at least one occurrence of R`,
    options: [`R* includes zero repetitions (ε), while R^+ requires at least one occurrence of R`, `R^+ includes ε, while R* does not`, `There is no difference`, `R^+ allows negative repetitions`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `R^+ is defined as RR*, ensuring the pattern occurs at least once.`,
    keyConcept: `Star vs Plus`,
    commonMistake: ``
  },
  {
    id: 'q_171',
    topicId: 'top_re_identities',
    text: `Which of the following is the identity element for the Union operation in regular expressions?`,
    correctAnswer: `∅`,
    options: [`∅`, `ε`, `Σ*`, `The expression itself`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `R + ∅ = R. Adding the empty language to any language yields the original language.`,
    keyConcept: `Identity for Union`,
    commonMistake: ``
  },
  {
    id: 'q_172',
    topicId: 'top_re_identities',
    text: `Which of the following is the identity element for Concatenation in regular expressions?`,
    correctAnswer: `ε`,
    options: [`ε`, `∅`, `Σ*`, `The expression itself`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Rε = εR = R. Concatenating the empty string does not change the strings in the language.`,
    keyConcept: `Identity for Concatenation`,
    commonMistake: ``
  },
  {
    id: 'q_173',
    topicId: 'top_re_identities',
    text: `What is the result of concatenating any regular expression R with the empty set ∅ (i.e., R∅)?`,
    correctAnswer: `∅`,
    options: [`∅`, `R`, `ε`, `R*`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `∅ acts as an annihilator for concatenation. You cannot form a string by concatenating from an empty set.`,
    keyConcept: `Annihilator for Concatenation`,
    commonMistake: ``
  },
  {
    id: 'q_174',
    topicId: 'top_re_identities',
    text: `Which identity represents the Idempotent Law for regular expressions?`,
    correctAnswer: `R + R = R`,
    options: [`R + R = R`, `R* = R`, `RS = SR`, `R + ∅ = ∅`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Set union of a set with itself is the same set: L(R) ∪ L(R) = L(R).`,
    keyConcept: `Idempotence`,
    commonMistake: ``
  },
  {
    id: 'q_175',
    topicId: 'top_re_identities',
    text: `Does Concatenation distribute over Union?`,
    correctAnswer: `Yes, R(S + T) = RS + RT`,
    options: [`Yes, R(S + T) = RS + RT`, `No`, `Only for finite languages`, `Yes, R(S + T) = (RS) + T`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Concatenation acts like multiplication and distributes over Union (addition).`,
    keyConcept: `Distributive Law`,
    commonMistake: ``
  },
  {
    id: 'q_176',
    topicId: 'top_re_identities',
    text: `Which identity correctly relates R* and ε?`,
    correctAnswer: `R* = ε + RR*`,
    options: [`R* = ε + RR*`, `R* = εR`, `R* = R + ε`, `R* = R*R* - ε`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `R* means 0 repetitions (ε) OR 1 or more repetitions (RR*).`,
    keyConcept: `Star Identity`,
    commonMistake: ``
  },
  {
    id: 'q_177',
    topicId: 'top_re_identities',
    text: `What is the evaluation of ∅*?`,
    correctAnswer: `ε`,
    options: [`ε`, `∅`, `Σ*`, `Undefined`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Repeating the empty set 0 times gives the empty string ε. Repeating it 1 or more times gives ∅. The union is ε.`,
    keyConcept: `Empty set star`,
    commonMistake: ``
  },
  {
    id: 'q_178',
    topicId: 'top_re_identities',
    text: `Is (a+b)* equivalent to a* + b*?`,
    correctAnswer: `No, a* + b* only generates strings of pure a's or pure b's`,
    options: [`No, a* + b* only generates strings of pure a's or pure b's`, `Yes, they are identical`, `No, (a+b)* cannot generate pure a's`, `Yes, by the distributive property`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `(a+b)* generates mixed strings like 'ab', while a*+b* cannot.`,
    keyConcept: `Star over Union`,
    commonMistake: ``
  },
  {
    id: 'q_179',
    topicId: 'top_re_identities',
    text: `Which of the following identities is true for the Kleene Star?`,
    correctAnswer: `(R*)* = R*`,
    options: [`(R*)* = R*`, `(R*)* = R`, `R* = R`, `R* = R + ∅`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Applying the star operator multiple times to the same expression does not generate any new strings.`,
    keyConcept: `Idempotence of Star`,
    commonMistake: ``
  },
  {
    id: 'q_180',
    topicId: 'top_re_identities',
    text: `Which expression is equivalent to (R + S)*?`,
    correctAnswer: `(R*S*)*`,
    options: [`(R*S*)*`, `R* + S*`, `R*S*`, `R + S*`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `(R*S*)* allows arbitrary alternations between sequences of R and sequences of S, which exactly matches (R+S)*.`,
    keyConcept: `Complex Star Identity`,
    commonMistake: ``
  },
  {
    id: 'q_181',
    topicId: 'top_fa_and_re',
    text: `According to Kleene's Theorem, what is the relationship between Finite Automata and Regular Expressions?`,
    correctAnswer: `They describe the exact same class of languages`,
    options: [`They describe the exact same class of languages`, `FAs describe a larger class of languages`, `REs describe a larger class of languages`, `They represent different classes of languages`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Kleene's theorem formally proves that FAs and REs are exactly equivalent in expressive power.`,
    keyConcept: `Kleene's Theorem`,
    commonMistake: ``
  },
  {
    id: 'q_182',
    topicId: 'top_fa_and_re',
    text: `To prove Kleene's Theorem, one must show conversions in both directions. Which conversions are required?`,
    correctAnswer: `FA to RE, and RE to FA`,
    options: [`FA to RE, and RE to FA`, `DFA to NFA, and NFA to DFA`, `RE to Context-Free Grammar, and FA to Pushdown Automata`, `FA to Turing Machine, and RE to Turing Machine`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Equivalence is proven by providing structural algorithms to convert from either model to the other.`,
    keyConcept: `Proof Structure`,
    commonMistake: ``
  },
  {
    id: 'q_183',
    topicId: 'top_fa_and_re',
    text: `When converting from a Regular Expression to an Automaton, what type of automaton is typically produced first by standard algorithms like Thompson's Construction?`,
    correctAnswer: `An NFA with ε-transitions`,
    options: [`An NFA with ε-transitions`, `A minimized DFA`, `A DFA without ε-transitions`, `A Pushdown Automaton`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The recursive nature of REs naturally maps to ε-transitions to connect sub-components.`,
    keyConcept: `RE to FA Output`,
    commonMistake: ``
  },
  {
    id: 'q_184',
    topicId: 'top_fa_and_re',
    text: `If a language L is recognized by an NFA, can it be described by a Regular Expression?`,
    correctAnswer: `Yes, because NFAs are equivalent to DFAs, which are equivalent to REs`,
    options: [`Yes, because NFAs are equivalent to DFAs, which are equivalent to REs`, `No, NFAs are more powerful`, `Only if it has no ε-transitions`, `Only if the NFA is minimized`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `All FA variants (DFA, NFA, ε-NFA) and Regular Expressions describe exactly the Regular Languages.`,
    keyConcept: `NFA to RE`,
    commonMistake: ``
  },
  {
    id: 'q_185',
    topicId: 'top_fa_and_re',
    text: `What is the primary significance of proving FAs and REs are equivalent?`,
    correctAnswer: `It unifies the procedural (FA) and declarative (RE) models of computation`,
    options: [`It unifies the procedural (FA) and declarative (RE) models of computation`, `It proves P = NP`, `It shows Turing Machines are unnecessary`, `It provides a way to minimize REs`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `It shows that specifying a pattern declaratively is exactly as powerful as building a procedural machine to parse it.`,
    keyConcept: `Significance of Equivalence`,
    commonMistake: ``
  },
  {
    id: 'q_186',
    topicId: 'top_fa_and_re',
    text: `Is the set of Regular Languages closed under conversion between REs and FAs?`,
    correctAnswer: `Yes, they define the exact same set`,
    options: [`Yes, they define the exact same set`, `No, converting to RE loses information`, `No, FAs can express more`, `Yes, but only for finite languages`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `They are perfectly equivalent definitions of Regular Languages.`,
    keyConcept: `Equivalence`,
    commonMistake: ``
  },
  {
    id: 'q_187',
    topicId: 'top_fa_and_re',
    text: `Can a non-regular language be described by a Regular Expression?`,
    correctAnswer: `No, REs only describe regular languages`,
    options: [`No, REs only describe regular languages`, `Yes, using the Kleene star`, `Yes, if the expression is infinitely long`, `No, unless it uses intersection`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `By definition, REs describe exactly the regular languages.`,
    keyConcept: `Limits of RE`,
    commonMistake: ``
  },
  {
    id: 'q_188',
    topicId: 'top_fa_and_re',
    text: `When an RE is converted to a DFA, is the resulting DFA unique?`,
    correctAnswer: `No, multiple structurally different DFAs can recognize the same language`,
    options: [`No, multiple structurally different DFAs can recognize the same language`, `Yes, the algorithm guarantees a unique DFA`, `Yes, but only if the RE has no stars`, `No, because DFAs cannot evaluate REs`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The specific DFA produced depends on the conversion algorithm. The language is the same, but the machine is not unique until minimized.`,
    keyConcept: `Uniqueness`,
    commonMistake: ``
  },
  {
    id: 'q_189',
    topicId: 'top_fa_and_re',
    text: `Which algorithm is commonly used as half of the proof of Kleene's theorem by converting an RE to an FA?`,
    correctAnswer: `Thompson's Construction`,
    options: [`Thompson's Construction`, `Arden's Theorem`, `State Elimination`, `Subset Construction`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Thompson's Construction systematically builds an ε-NFA from a Regular Expression.`,
    keyConcept: `Thompson's Construction`,
    commonMistake: ``
  },
  {
    id: 'q_190',
    topicId: 'top_fa_and_re',
    text: `Which method is commonly used as the other half of the proof of Kleene's theorem by converting an FA to an RE?`,
    correctAnswer: `State Elimination Method`,
    options: [`State Elimination Method`, `Subset Construction`, `Hopcroft's Algorithm`, `Thompson's Construction`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `State Elimination provides an algorithmic way to extract the Regular Expression from a Finite Automaton.`,
    keyConcept: `State Elimination`,
    commonMistake: ``
  },
  {
    id: 'q_191',
    topicId: 'top_dfa_to_re',
    text: `What is the general solution to the regular expression equation R = Q + RP, according to Arden's Theorem (assuming P does not contain ε)?`,
    correctAnswer: `R = QP*`,
    options: [`R = QP*`, `R = P*Q`, `R = Q*P`, `R = PQ*`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The recursion means R can be Q, QP, QPP, etc., which is algebraically denoted as QP*.`,
    keyConcept: `Arden's Theorem`,
    commonMistake: ``
  },
  {
    id: 'q_192',
    topicId: 'top_dfa_to_re',
    text: `To apply Arden's theorem uniquely, what condition must hold for R = Q + RP?`,
    correctAnswer: `P must not contain the empty string ε`,
    options: [`P must not contain the empty string ε`, `Q must not contain ε`, `R must be empty`, `P and Q must be identical`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `If P contains ε, the equation does not have a unique solution.`,
    keyConcept: `Arden's Condition`,
    commonMistake: ``
  },
  {
    id: 'q_193',
    topicId: 'top_dfa_to_re',
    text: `In the State Elimination method, what is the first preparatory step?`,
    correctAnswer: `Add a new start state and a new final state connected via ε-transitions to the original start and final states`,
    options: [`Add a new start state and a new final state connected via ε-transitions to the original start and final states`, `Remove all dead states`, `Minimize the DFA`, `Convert all transitions to Kleene stars`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Isolating the start and final states ensures we don't accidentally sever necessary paths when eliminating the original states.`,
    keyConcept: `State Elimination Preparation`,
    commonMistake: ``
  },
  {
    id: 'q_194',
    topicId: 'top_dfa_to_re',
    text: `When eliminating state q in a path p → q → r, what is the formula for the new direct edge p → r?`,
    correctAnswer: `(edge p→q) (loop q→q)* (edge q→r)`,
    options: [`(edge p→q) (loop q→q)* (edge q→r)`, `(edge p→q) + (edge q→r)`, `(edge p→q) (edge q→r)*`, `(edge p→r)*`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The path must enter q, loop on q any number of times, and then exit q to r.`,
    keyConcept: `Elimination Formula`,
    commonMistake: ``
  },
  {
    id: 'q_195',
    topicId: 'top_dfa_to_re',
    text: `If there is no self-loop on the state q being eliminated, what does the loop term (q→q)* become in the elimination formula?`,
    correctAnswer: `ε`,
    options: [`ε`, `∅`, `It becomes invalid`, `It remains as *`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `If there is no loop, the loop is taken 0 times, which evaluates to ε. The formula simplifies to (edge p→q)(edge q→r).`,
    keyConcept: `No loop case`,
    commonMistake: ``
  },
  {
    id: 'q_196',
    topicId: 'top_dfa_to_re',
    text: `If eliminating a state creates a new transition p → r, but an edge p → r already exists, what is the correct action?`,
    correctAnswer: `Label the edge with the Union (+) of the old label and the new label`,
    options: [`Label the edge with the Union (+) of the old label and the new label`, `Replace the old edge`, `Keep the old edge and discard the new one`, `State elimination fails in this case`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Parallel paths in an automaton represent a choice, which translates to the Union operator (+).`,
    keyConcept: `Parallel Paths`,
    commonMistake: ``
  },
  {
    id: 'q_197',
    topicId: 'top_dfa_to_re',
    text: `When do you stop eliminating states in the State Elimination method?`,
    correctAnswer: `When only the newly added start state and newly added final state remain`,
    options: [`When only the newly added start state and newly added final state remain`, `When all loops are removed`, `When the DFA becomes an NFA`, `When only one original state is left`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The final single edge remaining between the new start and new final state contains the complete regular expression.`,
    keyConcept: `Termination`,
    commonMistake: ``
  },
  {
    id: 'q_198',
    topicId: 'top_dfa_to_re',
    text: `Consider states 1, 2, 3. Edges: 1→2 labeled 'a', 2→2 labeled 'b', 2→3 labeled 'c'. Eliminating state 2 creates what edge from 1 to 3?`,
    correctAnswer: `ab*c`,
    options: [`ab*c`, `a+b*+c`, `(abc)*`, `a(b+c)*`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The path goes in via 'a', loops on 'b' any number of times, and exits via 'c'.`,
    keyConcept: `Basic Elimination`,
    commonMistake: ``
  },
  {
    id: 'q_199',
    topicId: 'top_dfa_to_re',
    text: `If a state q has incoming edges from states p1, p2 and outgoing edges to states r1, r2, how many new edges are created when q is eliminated?`,
    correctAnswer: `4`,
    options: [`4`, `2`, `0`, `8`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `You must connect every incoming node to every outgoing node: p1→r1, p1→r2, p2→r1, p2→r2.`,
    keyConcept: `Combinatorial elimination`,
    commonMistake: ``
  },
  {
    id: 'q_200',
    topicId: 'top_dfa_to_re',
    text: `If a DFA has no accept states, what is the resulting Regular Expression?`,
    correctAnswer: `∅`,
    options: [`∅`, `ε`, `Σ*`, `It depends on the start state`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `No accept states means the DFA accepts nothing, which is the empty language ∅.`,
    keyConcept: `Empty DFA`,
    commonMistake: ``
  },
  {
    id: 'q_201',
    topicId: 'top_re_to_fa',
    text: `Which algorithm structurally converts a Regular Expression into an ε-NFA?`,
    correctAnswer: `Thompson's Construction`,
    options: [`Thompson's Construction`, `State Elimination`, `Subset Construction`, `DFA Minimization`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Thompson's algorithm recursively builds an ε-NFA from an RE.`,
    keyConcept: `Thompson's Algorithm`,
    commonMistake: ``
  },
  {
    id: 'q_202',
    topicId: 'top_re_to_fa',
    text: `In Thompson's Construction, what does the automaton for a single symbol 'a' look like?`,
    correctAnswer: `Two states connected by a single transition labeled 'a'`,
    options: [`Two states connected by a single transition labeled 'a'`, `One state with a self-loop labeled 'a'`, `Three states with ε-transitions`, `A single accept state`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The base case is simply a start state, a final state, and an edge 'a' between them.`,
    keyConcept: `Base Case`,
    commonMistake: ``
  },
  {
    id: 'q_203',
    topicId: 'top_re_to_fa',
    text: `How is Union (R + S) constructed in Thompson's algorithm?`,
    correctAnswer: `A new start state branches via ε to the starts of R and S, and their finals connect via ε to a new final state`,
    options: [`A new start state branches via ε to the starts of R and S, and their finals connect via ε to a new final state`, `Merge the start states of R and S into one`, `Connect the final of R to the start of S`, `Add a self loop of R+S`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Branching with ε-transitions creates the 'OR' choice without consuming input.`,
    keyConcept: `Union Construction`,
    commonMistake: ``
  },
  {
    id: 'q_204',
    topicId: 'top_re_to_fa',
    text: `How is Concatenation (RS) constructed in Thompson's algorithm?`,
    correctAnswer: `Merge the final state of R with the start state of S`,
    options: [`Merge the final state of R with the start state of S`, `Add an ε-transition from the start of R to the start of S`, `Create a new start state pointing to both`, `Connect the final of S to the start of R`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `When R finishes successfully, it immediately feeds into the beginning of S.`,
    keyConcept: `Concatenation Construction`,
    commonMistake: ``
  },
  {
    id: 'q_205',
    topicId: 'top_re_to_fa',
    text: `How many new states are introduced when applying the Kleene Star (R*) in Thompson's construction?`,
    correctAnswer: `2`,
    options: [`2`, `1`, `0`, `4`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `A new start and a new final state are added to allow skipping R entirely and cleanly looping back.`,
    keyConcept: `Star Construction`,
    commonMistake: ``
  },
  {
    id: 'q_206',
    topicId: 'top_re_to_fa',
    text: `What is a guaranteed property of any ε-NFA generated by Thompson's construction?`,
    correctAnswer: `It has exactly one start state and one final state`,
    options: [`It has exactly one start state and one final state`, `It is deterministic`, `It has no ε-transitions`, `Every state is an accept state`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The construction rules mathematically preserve the invariant of exactly one start and one final state at every recursive step.`,
    keyConcept: `Thompson's Properties`,
    commonMistake: ``
  },
  {
    id: 'q_207',
    topicId: 'top_re_to_fa',
    text: `In Thompson's construction for R*, what structural addition allows the expression to evaluate to the empty string ε?`,
    correctAnswer: `An ε-transition from the newly added start state directly to the newly added final state`,
    options: [`An ε-transition from the newly added start state directly to the newly added final state`, `An ε-transition from the old final state to the old start state`, `Removing the transitions of R`, `Making every state an accept state`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `This direct ε-transition bypasses the internal machine R entirely, representing zero occurrences.`,
    keyConcept: `Star Bypass`,
    commonMistake: ``
  },
  {
    id: 'q_208',
    topicId: 'top_re_to_fa',
    text: `How many states will Thompson's construction produce for the simplest Regular Expression 'a'?`,
    correctAnswer: `2`,
    options: [`2`, `1`, `3`, `4`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `A start state, a transition 'a', and a final state.`,
    keyConcept: `State Counting`,
    commonMistake: ``
  },
  {
    id: 'q_209',
    topicId: 'top_re_to_fa',
    text: `Is the ε-NFA produced by Thompson's construction the smallest possible automaton for the RE?`,
    correctAnswer: `No, it often contains many redundant ε-transitions and states`,
    options: [`No, it often contains many redundant ε-transitions and states`, `Yes, it is minimal`, `Yes, but only for finite languages`, `No, but it is always a DFA`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Thompson's trades efficiency/minimality for structural simplicity and guaranteed linear construction time.`,
    keyConcept: `Minimality`,
    commonMistake: ``
  },
  {
    id: 'q_210',
    topicId: 'top_re_to_fa',
    text: `After generating an ε-NFA using Thompson's construction, how is it typically executed?`,
    correctAnswer: `By computing the ε-closure of states while processing characters, effectively performing subset construction on the fly`,
    options: [`By computing the ε-closure of states while processing characters, effectively performing subset construction on the fly`, `By running it backwards`, `By eliminating states`, `By using a stack`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `This approach evaluates the non-deterministic paths deterministically in software.`,
    keyConcept: `Execution`,
    commonMistake: ``
  },
  {
    id: 'q_211',
    topicId: 'top_re_apps',
    text: `Which component of a compiler relies heavily on Regular Expressions?`,
    correctAnswer: `Lexical Analyzer`,
    options: [`Lexical Analyzer`, `Syntax Analyzer`, `Semantic Analyzer`, `Code Optimizer`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Lexical analyzers (scanners) use REs to group characters into meaningful tokens like keywords and identifiers.`,
    keyConcept: `Lexical Analysis`,
    commonMistake: ``
  },
  {
    id: 'q_212',
    topicId: 'top_re_apps',
    text: `In standard text editors and utilities like grep, what is the primary use of Regular Expressions?`,
    correctAnswer: `Pattern matching and text search`,
    options: [`Pattern matching and text search`, `Syntax highlighting`, `Memory management`, `File compression`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `REs are the industry standard for defining search patterns in text processing.`,
    keyConcept: `Pattern Matching`,
    commonMistake: ``
  },
  {
    id: 'q_213',
    topicId: 'top_re_apps',
    text: `When validating a user's email address on a web form, why are Regular Expressions commonly used?`,
    correctAnswer: `They succinctly define the specific string structure required for a valid email format`,
    options: [`They succinctly define the specific string structure required for a valid email format`, `They encrypt the email address securely`, `They connect to a database to verify the user`, `They compress the email string`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Input validation relies on REs to ensure strings conform to specific structural rules.`,
    keyConcept: `Input Validation`,
    commonMistake: ``
  },
  {
    id: 'q_214',
    topicId: 'top_re_apps',
    text: `In the context of network security, how are Regular Expressions applied in Intrusion Detection Systems (IDS)?`,
    correctAnswer: `To define signatures that match known malicious payload patterns in network traffic`,
    options: [`To define signatures that match known malicious payload patterns in network traffic`, `To encrypt outgoing packets`, `To route packets to the correct IP address`, `To allocate bandwidth dynamically`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `IDS engines scan packet contents against a database of REs representing known attacks.`,
    keyConcept: `Network Security`,
    commonMistake: ``
  },
  {
    id: 'q_215',
    topicId: 'top_re_apps',
    text: `Can Regular Expressions be used to parse completely nested structures, like matching an arbitrary number of open and closed parentheses in source code?`,
    correctAnswer: `No, because standard REs cannot count arbitrarily nested structures`,
    options: [`No, because standard REs cannot count arbitrarily nested structures`, `Yes, by using the Kleene star`, `Yes, but it requires a very long RE`, `No, unless they are minimized`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Properly nested parentheses form a Context-Free Language, which exceeds the theoretical power of Regular Expressions.`,
    keyConcept: `Limitations of REs`,
    commonMistake: ``
  },
  {
    id: 'q_216',
    topicId: 'top_re_apps',
    text: `Which UNIX utility is fundamentally built around applying Regular Expressions to extract or transform text line-by-line?`,
    correctAnswer: `sed`,
    options: [`sed`, `ls`, `tar`, `chmod`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `sed (stream editor) uses REs to find and replace text patterns.`,
    keyConcept: `UNIX Utilities`,
    commonMistake: ``
  },
  {
    id: 'q_217',
    topicId: 'top_re_apps',
    text: `In modern programming languages, what does the backslash (\\) typically signify in a Regular Expression string?`,
    correctAnswer: `An escape character to indicate a literal character or a special character class`,
    options: [`An escape character to indicate a literal character or a special character class`, `A division operator`, `The end of the regular expression`, `A substitution command`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Escape characters allow REs to match literals like '*' or '+' that would otherwise act as operators.`,
    keyConcept: `Escape Characters`,
    commonMistake: ``
  },
  {
    id: 'q_218',
    topicId: 'top_re_apps',
    text: `If a software application needs to extract all phone numbers from a document, what makes a Regular Expression the optimal tool?`,
    correctAnswer: `It allows searching for a generalized pattern of digits and dashes, rather than searching for specific known numbers`,
    options: [`It allows searching for a generalized pattern of digits and dashes, rather than searching for specific known numbers`, `It is faster than a hash map lookup`, `It can automatically dial the numbers`, `It requires no memory to execute`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `REs excel at defining generalized patterns (e.g., three digits, a dash, four digits) rather than literal strings.`,
    keyConcept: `Generalized Search`,
    commonMistake: ``
  },
  {
    id: 'q_219',
    topicId: 'top_re_apps',
    text: `What is a practical limitation of using complex Regular Expressions in production software?`,
    correctAnswer: `Certain RE patterns can cause catastrophic backtracking, leading to severe performance degradation`,
    options: [`Certain RE patterns can cause catastrophic backtracking, leading to severe performance degradation`, `They cannot match uppercase letters`, `They take exponential space in memory`, `They must be compiled at runtime only`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Poorly written REs processed by backtracking engines can exhibit exponential time complexity on specific mismatched strings.`,
    keyConcept: `Catastrophic Backtracking`,
    commonMistake: ``
  },
  {
    id: 'q_220',
    topicId: 'top_re_apps',
    text: `Why do some modern regex engines (like those in Python or Java) support features like 'backreferences', which are not part of standard mathematical Regular Expressions?`,
    correctAnswer: `To provide convenience for string manipulation, even though it breaks strict theoretical regularity`,
    options: [`To provide convenience for string manipulation, even though it breaks strict theoretical regularity`, `Because backreferences are required by Kleene's Theorem`, `To ensure the expressions evaluate in constant time`, `To convert them to Pushdown Automata`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Practical regex engines extend the mathematical definition to handle non-regular languages (like matching the exact same word twice).`,
    keyConcept: `Theory vs Practice`,
    commonMistake: ``
  },
  {
    id: 'q_221',
    topicId: 'top_rg_def',
    text: `What is the primary function of a Regular Grammar?`,
    correctAnswer: `To generate exactly the class of Regular Languages`,
    options: [`To generate exactly the class of Regular Languages`, `To generate Context-Free Languages`, `To parse mathematical equations`, `To minimize Finite Automata`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Regular Grammars are the generative counterpart to Finite Automata, producing exactly the regular languages.`,
    keyConcept: `Function of Regular Grammar`,
    commonMistake: ``
  },
  {
    id: 'q_222',
    topicId: 'top_rg_def',
    text: `A formal grammar is defined as a 4-tuple G = (V, T, P, S). What does 'T' represent?`,
    correctAnswer: `A finite set of terminals`,
    options: [`A finite set of terminals`, `The transition function`, `A finite set of variables`, `The start symbol`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `T stands for terminals, the actual symbols of the alphabet that make up the final generated strings.`,
    keyConcept: `Grammar Tuple`,
    commonMistake: ``
  },
  {
    id: 'q_223',
    topicId: 'top_rg_def',
    text: `Which of the following production rule formats is strictly allowed in a Right-Linear Regular Grammar?`,
    correctAnswer: `A → aB or A → a or A → ε`,
    options: [`A → aB or A → a or A → ε`, `A → Ba or A → a or A → ε`, `A → aBb`, `A → AB`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `In a right-linear grammar, all non-terminals (variables) must appear strictly at the right end of the production.`,
    keyConcept: `Right-Linear Rules`,
    commonMistake: ``
  },
  {
    id: 'q_224',
    topicId: 'top_rg_def',
    text: `Which of the following production rule formats is strictly allowed in a Left-Linear Regular Grammar?`,
    correctAnswer: `A → Ba or A → a or A → ε`,
    options: [`A → Ba or A → a or A → ε`, `A → aB or A → a or A → ε`, `A → aBb`, `A → AB`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `In a left-linear grammar, all non-terminals (variables) must appear strictly at the left end of the production.`,
    keyConcept: `Left-Linear Rules`,
    commonMistake: ``
  },
  {
    id: 'q_225',
    topicId: 'top_rg_def',
    text: `If a grammar contains both A → aB (right-linear) and C → Dc (left-linear) production rules, is it guaranteed to be a Regular Grammar?`,
    correctAnswer: `No, mixing left and right linear rules can generate non-regular languages`,
    options: [`No, mixing left and right linear rules can generate non-regular languages`, `Yes, it is still a regular grammar`, `Yes, it generates a finite language`, `No, because it becomes a Turing Machine`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `A regular grammar must be strictly right-linear OR strictly left-linear. Mixing them creates a linear grammar, which can generate non-regular languages like a^n b^n.`,
    keyConcept: `Mixed Rules`,
    commonMistake: ``
  },
  {
    id: 'q_226',
    topicId: 'top_rg_def',
    text: `What does the symbol 'S' represent in the formal definition of a grammar?`,
    correctAnswer: `The designated start variable`,
    options: [`The designated start variable`, `The set of states`, `The set of symbols`, `A terminal string`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `S is the start variable (non-terminal) from which all string generation derivations must begin.`,
    keyConcept: `Start Symbol`,
    commonMistake: ``
  },
  {
    id: 'q_227',
    topicId: 'top_rg_def',
    text: `In a Regular Grammar, what happens when a derivation applies a rule of the form A → a (where 'a' is a terminal)?`,
    correctAnswer: `The derivation process terminates for that branch because no variables remain`,
    options: [`The derivation process terminates for that branch because no variables remain`, `The grammar generates an infinite string`, `The grammar returns to the start symbol`, `A new variable is created`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Terminals cannot be replaced. Without non-terminals remaining, the string generation is complete.`,
    keyConcept: `Terminal Derivation`,
    commonMistake: ``
  },
  {
    id: 'q_228',
    topicId: 'top_rg_def',
    text: `Which class of grammars in the Chomsky Hierarchy corresponds to Regular Grammars?`,
    correctAnswer: `Type 3 Grammars`,
    options: [`Type 3 Grammars`, `Type 2 Grammars`, `Type 1 Grammars`, `Type 0 Grammars`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `In the Chomsky hierarchy, Type 3 grammars are the most restricted class, corresponding to regular languages.`,
    keyConcept: `Chomsky Hierarchy`,
    commonMistake: ``
  },
  {
    id: 'q_229',
    topicId: 'top_rg_def',
    text: `Can a Regular Grammar generate the empty string ε?`,
    correctAnswer: `Yes, if there is a production rule of the form A → ε`,
    options: [`Yes, if there is a production rule of the form A → ε`, `No, grammars cannot generate empty strings`, `Only if the grammar has no variables`, `Only in left-linear grammars`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The empty string is a valid regular language component, generated via an ε-production.`,
    keyConcept: `Empty String Generation`,
    commonMistake: ``
  },
  {
    id: 'q_230',
    topicId: 'top_rg_def',
    text: `Why are Regular Grammars computationally equivalent to Finite Automata?`,
    correctAnswer: `Because the strict linear progression of variables exactly models the state-by-state transitions of an FA`,
    options: [`Because the strict linear progression of variables exactly models the state-by-state transitions of an FA`, `Because both use a stack`, `Because both are deterministic`, `Because Kleene's theorem prohibits variables`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Appending a terminal and moving to a new variable maps perfectly to consuming a character and moving to a new state.`,
    keyConcept: `Grammar vs FA equivalence`,
    commonMistake: ``
  },
  {
    id: 'q_231',
    topicId: 'top_rg_and_fa',
    text: `What is the theoretical relationship between Regular Grammars and Finite Automata?`,
    correctAnswer: `They are completely equivalent; both describe exactly the class of Regular Languages`,
    options: [`They are completely equivalent; both describe exactly the class of Regular Languages`, `Finite Automata are more powerful`, `Regular Grammars can generate Context-Free Languages`, `They are unrelated concepts`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Any language generated by a RG can be accepted by an FA, and vice versa.`,
    keyConcept: `Equivalence`,
    commonMistake: ``
  },
  {
    id: 'q_232',
    topicId: 'top_rg_and_fa',
    text: `When equating a Right-Linear Grammar to a Finite Automaton, what do the non-terminal variables in the grammar represent?`,
    correctAnswer: `The states of the Finite Automaton`,
    options: [`The states of the Finite Automaton`, `The input alphabet`, `The transition arrows`, `The final accept states`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Each variable acts as a state that dictates what symbols can be generated (consumed) next.`,
    keyConcept: `Variables as States`,
    commonMistake: ``
  },
  {
    id: 'q_233',
    topicId: 'top_rg_and_fa',
    text: `When equating a Right-Linear Grammar to an FA, what does the start variable S represent?`,
    correctAnswer: `The start state of the automaton`,
    options: [`The start state of the automaton`, `The final state of the automaton`, `The first character of the string`, `The transition function`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Both derivation and computation must begin at exactly one designated starting point.`,
    keyConcept: `Start State`,
    commonMistake: ``
  },
  {
    id: 'q_234',
    topicId: 'top_rg_and_fa',
    text: `In the mapping between a Right-Linear Grammar and an FA, what does a production rule A → aB signify?`,
    correctAnswer: `A transition from state A to state B labeled with input symbol 'a'`,
    options: [`A transition from state A to state B labeled with input symbol 'a'`, `A transition from B to A`, `A final state B`, `An empty transition`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Generating 'a' and moving to 'B' is structurally identical to reading 'a' and transitioning to state B.`,
    keyConcept: `Production to Transition`,
    commonMistake: ``
  },
  {
    id: 'q_235',
    topicId: 'top_rg_and_fa',
    text: `What does a terminating production rule A → a (or A → ε) signify in the corresponding Finite Automaton?`,
    correctAnswer: `A transition into a final accept state`,
    options: [`A transition into a final accept state`, `A transition back to the start state`, `A dead state`, `A non-deterministic choice`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Terminating the derivation means the string is complete and valid, which corresponds to halting in an accept state.`,
    keyConcept: `Terminating Production`,
    commonMistake: ``
  },
  {
    id: 'q_236',
    topicId: 'top_rg_and_fa',
    text: `If a Right-Linear Grammar has a rule A → aB and A → aC, what property will the corresponding Finite Automaton exhibit?`,
    correctAnswer: `Non-determinism (it will be an NFA)`,
    options: [`Non-determinism (it will be an NFA)`, `Determinism`, `It will reject the string`, `It will loop infinitely`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Multiple rules for the same variable and terminal mean multiple outgoing transitions for the same symbol from a state, which defines an NFA.`,
    keyConcept: `Non-determinism`,
    commonMistake: ``
  },
  {
    id: 'q_237',
    topicId: 'top_rg_and_fa',
    text: `Why is a strictly Right-Linear Grammar preferred over a Left-Linear Grammar when mapping directly to standard Finite Automata?`,
    correctAnswer: `Because FAs process strings from left to right, matching the right-linear generation of appending symbols to the right`,
    options: [`Because FAs process strings from left to right, matching the right-linear generation of appending symbols to the right`, `Because Left-Linear Grammars cannot generate regular languages`, `Because Left-Linear Grammars are ambiguous`, `Because FAs use stacks`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Right-linear builds the string left-to-right (a, ab, abc), exactly as an FA reads it.`,
    keyConcept: `Right vs Left Linear`,
    commonMistake: ``
  },
  {
    id: 'q_238',
    topicId: 'top_rg_and_fa',
    text: `If you convert a Left-Linear Grammar directly to an automaton without reversing it, what does the automaton effectively do?`,
    correctAnswer: `It processes the string from right to left`,
    options: [`It processes the string from right to left`, `It rejects all strings`, `It acts as a pushdown automaton`, `It loops infinitely`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Left-linear grammars build strings by prepending. To parse this directly, the FA would have to read backwards.`,
    keyConcept: `Left Linear Execution`,
    commonMistake: ``
  },
  {
    id: 'q_239',
    topicId: 'top_rg_and_fa',
    text: `Can a Regular Grammar generate a language that a DFA cannot accept?`,
    correctAnswer: `No, because every Regular Grammar language is regular, and every regular language has a DFA`,
    options: [`No, because every Regular Grammar language is regular, and every regular language has a DFA`, `Yes, if it uses ε-productions`, `Yes, if it is non-deterministic`, `No, unless it is a Left-Linear grammar`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Kleene's theorem and grammar equivalence guarantee DFAs can accept anything a RG generates.`,
    keyConcept: `Equivalence Bounds`,
    commonMistake: ``
  },
  {
    id: 'q_240',
    topicId: 'top_rg_and_fa',
    text: `In the conversion from RG to FA, is it necessary to create a new, separate final state for rules like A → a?`,
    correctAnswer: `Yes, it is the standard procedure to ensure the derivation terminates in a valid accept state`,
    options: [`Yes, it is the standard procedure to ensure the derivation terminates in a valid accept state`, `No, state A becomes the final state`, `No, the start state becomes final`, `Yes, but only if 'a' is ε`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `A rule A → a implies generating 'a' and stopping. In the FA, this means from state A, read 'a' and go to an accept state.`,
    keyConcept: `Final State Creation`,
    commonMistake: ``
  },
  {
    id: 'q_241',
    topicId: 'top_fa_to_rg',
    text: `When converting a DFA to a Right-Linear Grammar, what does each state of the DFA become?`,
    correctAnswer: `A variable (non-terminal) in the grammar`,
    options: [`A variable (non-terminal) in the grammar`, `A production rule`, `A terminal symbol`, `The start symbol`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `States map directly to non-terminal variables representing the current condition of the generation.`,
    keyConcept: `State mapping`,
    commonMistake: ``
  },
  {
    id: 'q_242',
    topicId: 'top_fa_to_rg',
    text: `Given a transition δ(q1, a) = q2 in a DFA, what production rule is added to the corresponding Right-Linear Grammar?`,
    correctAnswer: `q1 → a q2`,
    options: [`q1 → a q2`, `q2 → a q1`, `q1 → q2 a`, `q1 → a`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Being in state q1 and reading 'a' to reach q2 translates to variable q1 generating 'a' and becoming variable q2.`,
    keyConcept: `Transition mapping`,
    commonMistake: ``
  },
  {
    id: 'q_243',
    topicId: 'top_fa_to_rg',
    text: `If a state q_f is a final (accept) state in the DFA, what production rule must be added for its corresponding variable?`,
    correctAnswer: `q_f → ε`,
    options: [`q_f → ε`, `q_f → a`, `q_f → q_f`, `No rule is added`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Accepting a string means the generation can halt at this point without generating any more characters.`,
    keyConcept: `Final state mapping`,
    commonMistake: ``
  },
  {
    id: 'q_244',
    topicId: 'top_fa_to_rg',
    text: `Consider a DFA with a start state q0. What becomes the start symbol of the generated grammar?`,
    correctAnswer: `q0`,
    options: [`q0`, `A new variable S`, `ε`, `The final state`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Generation must begin exactly where the DFA begins reading the string.`,
    keyConcept: `Start symbol mapping`,
    commonMistake: ``
  },
  {
    id: 'q_245',
    topicId: 'top_fa_to_rg',
    text: `If a DFA transition is δ(q1, a) = q2, and q2 is a final state, which of the following alternative production rules can be added to bypass creating ε-rules?`,
    correctAnswer: `q1 → a`,
    options: [`q1 → a`, `q2 → a`, `q1 → ε`, `q2 → a q1`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `If moving to q2 means the string can be accepted, then q1 can just generate 'a' and terminate the derivation.`,
    keyConcept: `Alternative termination`,
    commonMistake: ``
  },
  {
    id: 'q_246',
    topicId: 'top_fa_to_rg',
    text: `Does converting a DFA to a Regular Grammar preserve determinism in the grammatical structure?`,
    correctAnswer: `Yes, for any variable A and terminal a, there will be at most one rule A → aB`,
    options: [`Yes, for any variable A and terminal a, there will be at most one rule A → aB`, `No, the resulting grammar is always ambiguous`, `No, grammars have no concept related to determinism`, `Yes, but only if the DFA is minimized`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Because a DFA has exactly one transition for a given state and symbol, the grammar will have exactly one matching production.`,
    keyConcept: `Determinism preservation`,
    commonMistake: ``
  },
  {
    id: 'q_247',
    topicId: 'top_fa_to_rg',
    text: `Convert this DFA segment to a grammar rule: From state A, upon reading '0', loop back to state A.`,
    correctAnswer: `A → 0 A`,
    options: [`A → 0 A`, `A → A 0`, `A → 0`, `0 → A 0`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The variable A generates a '0' and remains variable A.`,
    keyConcept: `Loop mapping`,
    commonMistake: ``
  },
  {
    id: 'q_248',
    topicId: 'top_fa_to_rg',
    text: `If the start state of an FA is also a final state, what rule will appear in the grammar?`,
    correctAnswer: `S → ε (where S is the start variable)`,
    options: [`S → ε (where S is the start variable)`, `S → S`, `S → ∅`, `No special rule is needed`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `If the start state is final, the FA accepts the empty string, so the grammar must be able to generate it immediately.`,
    keyConcept: `Start state as final`,
    commonMistake: ``
  },
  {
    id: 'q_249',
    topicId: 'top_fa_to_rg',
    text: `Can this conversion algorithm be applied to an NFA as well as a DFA?`,
    correctAnswer: `Yes, the exact same rules apply, resulting in a Right-Linear Grammar`,
    options: [`Yes, the exact same rules apply, resulting in a Right-Linear Grammar`, `No, NFAs must be converted to DFAs first`, `Only if the NFA has no ε-transitions`, `No, NFAs result in Context-Free Grammars`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Multiple transitions for the same symbol in an NFA simply result in multiple production rules (e.g., A → aB and A → aC), which is perfectly valid.`,
    keyConcept: `NFA application`,
    commonMistake: ``
  },
  {
    id: 'q_250',
    topicId: 'top_fa_to_rg',
    text: `What happens to 'dead states' (states that cannot reach a final state) during conversion?`,
    correctAnswer: `They generate variables with production rules, but derivations entering these variables can never terminate into purely terminal strings`,
    options: [`They generate variables with production rules, but derivations entering these variables can never terminate into purely terminal strings`, `They are automatically ignored`, `They generate ε-productions`, `They cause the grammar to be invalid`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The rules exist, but since there is no path to a final state, there is no path to an A → ε rule, meaning the derivation never finishes.`,
    keyConcept: `Dead states`,
    commonMistake: ``
  },
  {
    id: 'q_251',
    topicId: 'top_rg_to_fa',
    text: `When converting a Right-Linear Grammar to an FA, what is the first structural step?`,
    correctAnswer: `Create a state for every variable, plus one special new final state`,
    options: [`Create a state for every variable, plus one special new final state`, `Create a state for every terminal`, `Create a single start state`, `Minimize the grammar`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Variables become states. The special final state is needed as a destination for terminating rules like A → a.`,
    keyConcept: `Initial setup`,
    commonMistake: ``
  },
  {
    id: 'q_252',
    topicId: 'top_rg_to_fa',
    text: `Given a production rule A → bC in the grammar, what transition is added to the FA?`,
    correctAnswer: `A transition from state A to state C labeled 'b'`,
    options: [`A transition from state A to state C labeled 'b'`, `A transition from C to A labeled 'b'`, `A transition from A to C labeled 'C'`, `A transition from start to A labeled 'b'`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The variable A generates 'b' and becomes C, mapping to transitioning from state A to C on input 'b'.`,
    keyConcept: `Production mapping`,
    commonMistake: ``
  },
  {
    id: 'q_253',
    topicId: 'top_rg_to_fa',
    text: `Given a terminating production rule A → c in the grammar, what transition is added to the FA?`,
    correctAnswer: `A transition from state A to the special final state labeled 'c'`,
    options: [`A transition from state A to the special final state labeled 'c'`, `A transition from state A to itself labeled 'c'`, `An ε-transition to state c`, `A transition from the start state to A`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The derivation halts upon generating 'c', so the FA must transition to an accept state upon reading 'c'.`,
    keyConcept: `Terminating rule mapping`,
    commonMistake: ``
  },
  {
    id: 'q_254',
    topicId: 'top_rg_to_fa',
    text: `If a grammar contains the rule A → ε, what happens to state A in the resulting FA?`,
    correctAnswer: `State A is marked as a final (accept) state`,
    options: [`State A is marked as a final (accept) state`, `An ε-transition is drawn to the start state`, `State A is deleted`, `An ε-transition is drawn to the special final state`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Generating ε means the derivation can successfully halt at A, making A an accept state.`,
    keyConcept: `Epsilon rule mapping`,
    commonMistake: ``
  },
  {
    id: 'q_255',
    topicId: 'top_rg_to_fa',
    text: `What type of automaton is typically produced by the direct conversion of a Regular Grammar to an FA?`,
    correctAnswer: `An NFA`,
    options: [`An NFA`, `A minimal DFA`, `A Pushdown Automaton`, `A DFA`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Grammars naturally contain non-determinism (e.g., A → bC and A → bD), which maps directly to an NFA.`,
    keyConcept: `Resulting machine type`,
    commonMistake: ``
  },
  {
    id: 'q_256',
    topicId: 'top_rg_to_fa',
    text: `If the start variable of the grammar is S, what is the start state of the FA?`,
    correctAnswer: `The state corresponding to variable S`,
    options: [`The state corresponding to variable S`, `The special final state`, `A newly created empty state`, `Any state with an outgoing transition`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The derivation begins at S, so the computation must begin at state S.`,
    keyConcept: `Start state mapping`,
    commonMistake: ``
  },
  {
    id: 'q_257',
    topicId: 'top_rg_to_fa',
    text: `Consider a grammar with rules S → 0A, A → 1. How many states does the resulting FA have?`,
    correctAnswer: `3`,
    options: [`3`, `2`, `4`, `1`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `State S, state A, and the special final state (for the A → 1 rule).`,
    keyConcept: `State count calculation`,
    commonMistake: ``
  },
  {
    id: 'q_258',
    topicId: 'top_rg_to_fa',
    text: `Why is a special final state necessary when converting RG to FA?`,
    correctAnswer: `To provide a destination state for terminating rules of the form A → a`,
    options: [`To provide a destination state for terminating rules of the form A → a`, `To make the machine deterministic`, `To handle ε-productions`, `To prevent infinite loops`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `A transition requires a destination. A → a means 'consume a and accept'. The special final state acts as that accepting destination.`,
    keyConcept: `Purpose of special final state`,
    commonMistake: ``
  },
  {
    id: 'q_259',
    topicId: 'top_rg_to_fa',
    text: `If a Right-Linear Grammar has multiple rules for the same variable and terminal (e.g., A → 0B, A → 0C), what happens in the FA?`,
    correctAnswer: `State A will have multiple outgoing transitions on '0', making it an NFA`,
    options: [`State A will have multiple outgoing transitions on '0', making it an NFA`, `The conversion fails`, `One rule is ignored`, `A new terminal is created`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `This directly translates to non-deterministic branching in the automaton.`,
    keyConcept: `Non-determinism mapping`,
    commonMistake: ``
  },
  {
    id: 'q_260',
    topicId: 'top_rg_to_fa',
    text: `Can this conversion be used for Left-Linear Grammars directly to yield a standard left-to-right FA?`,
    correctAnswer: `No, converting Left-Linear directly yields an FA that reads strings backwards`,
    options: [`No, converting Left-Linear directly yields an FA that reads strings backwards`, `Yes, it works identically`, `No, Left-Linear grammars cannot be converted to FAs`, `Yes, but the FA must be deterministic`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Left-linear grammars build strings by prepending. To get a standard left-to-right FA, one must reverse the grammar, apply the right-linear algorithm, and then reverse the resulting NFA.`,
    keyConcept: `Left-linear conversion`,
    commonMistake: ``
  },
  {
    id: 'q_261',
    topicId: 'top_pump_rl',
    text: `What is the formal purpose of the Pumping Lemma for Regular Languages?`,
    correctAnswer: `To prove that a specific language is NOT regular by contradiction`,
    options: [`To prove that a specific language is NOT regular by contradiction`, `To prove that a language IS regular`, `To convert an NFA to a DFA`, `To minimize a Finite Automaton`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `It provides a necessary condition for regularity. Failing the condition proves non-regularity.`,
    keyConcept: `Purpose of Pumping Lemma`,
    commonMistake: ``
  },
  {
    id: 'q_262',
    topicId: 'top_pump_rl',
    text: `In the formal statement of the Pumping Lemma, for a regular language L, what is 'p'?`,
    correctAnswer: `A constant integer ≥ 1 known as the pumping length, which depends only on L`,
    options: [`A constant integer ≥ 1 known as the pumping length, which depends only on L`, `The length of the chosen string s`, `The number of times the string is pumped`, `The number of non-terminals in the grammar`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The pumping length p represents (conceptually) the number of states in the DFA that recognizes L.`,
    keyConcept: `Pumping length p`,
    commonMistake: ``
  },
  {
    id: 'q_263',
    topicId: 'top_pump_rl',
    text: `In the Pumping Lemma, the string s is decomposed into s = xyz. What condition restricts the length of the substring 'y'?`,
    correctAnswer: `|y| > 0`,
    options: [`|y| > 0`, `|y| ≥ 0`, `|y| = p`, `|y| < p`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The substring y (the loop) must contain at least one character, otherwise pumping it has no effect.`,
    keyConcept: `Condition: |y| > 0`,
    commonMistake: ``
  },
  {
    id: 'q_264',
    topicId: 'top_pump_rl',
    text: `What condition restricts the position of the substring 'y' in the Pumping Lemma?`,
    correctAnswer: `|xy| ≤ p`,
    options: [`|xy| ≤ p`, `|xy| > p`, `|xy| = 0`, `|xy| ≥ p`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `By the Pigeonhole Principle, the first repetition of a state (the loop) must occur within the first p characters.`,
    keyConcept: `Condition: |xy| <= p`,
    commonMistake: ``
  },
  {
    id: 'q_265',
    topicId: 'top_pump_rl',
    text: `What does the Pumping Lemma state must be true for all i ≥ 0?`,
    correctAnswer: `xy^iz ∈ L`,
    options: [`xy^iz ∈ L`, `xy^iz ∉ L`, `x^iyz ∈ L`, `xyz^i ∈ L`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `If you repeat the loop substring 'y' any number of times (i), the resulting string must still be in the language.`,
    keyConcept: `Pumping condition`,
    commonMistake: ``
  },
  {
    id: 'q_266',
    topicId: 'top_pump_rl',
    text: `In a formal proof using the Pumping Lemma, who chooses the string 's'?`,
    correctAnswer: `The prover chooses s, but it must be in L and satisfy |s| ≥ p`,
    options: [`The prover chooses s, but it must be in L and satisfy |s| ≥ p`, `The adversary chooses s`, `s is always fixed as a^p b^p`, `s is randomly generated`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `You (the prover) select a strategic string s to force the adversary's decomposition into an unavoidable contradiction.`,
    keyConcept: `Quantifiers: Choosing s`,
    commonMistake: ``
  },
  {
    id: 'q_267',
    topicId: 'top_pump_rl',
    text: `In a formal proof using the Pumping Lemma, who chooses the decomposition s = xyz?`,
    correctAnswer: `The adversary chooses the decomposition; the proof must hold for ALL valid decompositions`,
    options: [`The adversary chooses the decomposition; the proof must hold for ALL valid decompositions`, `The prover chooses the most convenient decomposition`, `The decomposition is always x=ε, y=s, z=ε`, `The decomposition is random`],
    difficulty: 5,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `This is the most critical quantifier trap. You cannot assume y is a specific substring; you must prove the contradiction occurs for ANY valid xyz.`,
    keyConcept: `Quantifiers: Choosing xyz`,
    commonMistake: ``
  },
  {
    id: 'q_268',
    topicId: 'top_pump_rl',
    text: `If you choose to pump with i = 0 (yielding xz), what does this conceptually represent in the DFA?`,
    correctAnswer: `Bypassing the loop entirely`,
    options: [`Bypassing the loop entirely`, `Traversing the loop backwards`, `Going to a dead state`, `Rejecting the string`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Since y is the loop, repeating it 0 times means you take the path that skips the loop.`,
    keyConcept: `Pumping down`,
    commonMistake: ``
  },
  {
    id: 'q_269',
    topicId: 'top_pump_rl',
    text: `What mathematical principle guarantees the existence of the loop 'y'?`,
    correctAnswer: `The Pigeonhole Principle`,
    options: [`The Pigeonhole Principle`, `Mathematical Induction`, `De Morgan's Laws`, `The Halting Problem`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `If a path processes p characters, it visits p+1 states. If the DFA has only p states, at least one state must be visited twice.`,
    keyConcept: `Pigeonhole Principle`,
    commonMistake: ``
  },
  {
    id: 'q_270',
    topicId: 'top_pump_rl',
    text: `If a language satisfies all conditions of the Pumping Lemma, is it definitely regular?`,
    correctAnswer: `No, there are non-regular languages that satisfy the Pumping Lemma`,
    options: [`No, there are non-regular languages that satisfy the Pumping Lemma`, `Yes, it is a sufficient condition`, `Yes, but only if the alphabet is binary`, `No, it must be a Context-Free language`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The lemma is a necessary condition, but not a sufficient one. (e.g., L = {a^i b^j c^k | i,j,k ≥ 0 and if i=1 then j=k} is non-regular but pumps).`,
    keyConcept: `Necessary vs Sufficient`,
    commonMistake: ``
  },
  {
    id: 'q_271',
    topicId: 'top_pump_rl_apps',
    text: `When proving L = {a^n b^n | n ≥ 0} is not regular, what is the strategically best choice for the string s?`,
    correctAnswer: `s = a^p b^p`,
    options: [`s = a^p b^p`, `s = a b`, `s = a^n b^n`, `s = a^p`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Choosing a^p b^p forces the first p characters to be entirely 'a's, ensuring that the substring 'y' must consist solely of 'a's.`,
    keyConcept: `Strategic Choice of s`,
    commonMistake: ``
  },
  {
    id: 'q_272',
    topicId: 'top_pump_rl_apps',
    text: `For L = {a^n b^n}, if s = a^p b^p, what does the condition |xy| ≤ p logically enforce?`,
    correctAnswer: `The substring 'y' consists entirely of 'a's`,
    options: [`The substring 'y' consists entirely of 'a's`, `The substring 'y' consists entirely of 'b's`, `The substring 'y' crosses the boundary between a and b`, `The substring 'y' is empty`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Since xy is at most length p, and the first p characters are all 'a's, y cannot contain any 'b's.`,
    keyConcept: `Forcing y's composition`,
    commonMistake: ``
  },
  {
    id: 'q_273',
    topicId: 'top_pump_rl_apps',
    text: `In the proof for L = {a^n b^n}, after determining y is only 'a's, what happens when you pump with i=2?`,
    correctAnswer: `The number of 'a's increases while the number of 'b's remains unchanged, violating the n=n condition`,
    options: [`The number of 'a's increases while the number of 'b's remains unchanged, violating the n=n condition`, `The number of 'b's increases`, `The string remains in L`, `The string becomes empty`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The resulting string has p+|y| 'a's and p 'b's. Since |y| > 0, they are no longer equal.`,
    keyConcept: `Deriving the contradiction`,
    commonMistake: ``
  },
  {
    id: 'q_274',
    topicId: 'top_pump_rl_apps',
    text: `Why is the informal rule 'Finite Automata cannot count' slightly inaccurate?`,
    correctAnswer: `Finite Automata can count up to a fixed, finite maximum (like modulo counting); they only fail at unbounded counting`,
    options: [`Finite Automata can count up to a fixed, finite maximum (like modulo counting); they only fail at unbounded counting`, `Finite Automata can count infinitely`, `Finite Automata cannot count at all`, `Only Pushdown Automata can count modulo`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `A DFA can easily accept 'strings with exactly 5 a's' or 'even length strings'. It fails on unbounded parity requirements like a^n b^n.`,
    keyConcept: `Unbounded Counting`,
    commonMistake: ``
  },
  {
    id: 'q_275',
    topicId: 'top_pump_rl_apps',
    text: `When proving L = {ww | w ∈ {a,b}*} is not regular, what is a strong adversarial choice for s?`,
    correctAnswer: `s = a^p b a^p b`,
    options: [`s = a^p b a^p b`, `s = a^p a^p`, `s = a b a b`, `s = w w`],
    difficulty: 5,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Choosing a^p b a^p b forces y to be entirely 'a's in the first half. Pumping it imbalances the symmetry between the two halves.`,
    keyConcept: `Advanced Choice of s`,
    commonMistake: ``
  },
  {
    id: 'q_276',
    topicId: 'top_pump_rl_apps',
    text: `If you attempt to prove L = {a^n b^n} is non-regular by choosing s = a^(p/2) b^(p/2), what complication arises?`,
    correctAnswer: `The substring y might contain a mix of 'a's and 'b's, requiring you to analyze multiple complex cases`,
    options: [`The substring y might contain a mix of 'a's and 'b's, requiring you to analyze multiple complex cases`, `The length of s is less than p`, `The string is not in L`, `You cannot pump a mixed string`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `If |xy| ≤ p crosses the midpoint, y could be a^j, b^k, or a^j b^k. You must prove ALL cases fail, making the proof unnecessarily difficult.`,
    keyConcept: `Poor Choice of s`,
    commonMistake: ``
  },
  {
    id: 'q_277',
    topicId: 'top_pump_rl_apps',
    text: `Prove L = {a^p | p is prime} is not regular. After choosing s = a^q (where q is prime ≥ p), what is a valid contradiction strategy for pumping y (length k)?`,
    correctAnswer: `Pump with i = q + 1, making the new length q + qk = q(1+k), which is a composite number`,
    options: [`Pump with i = q + 1, making the new length q + qk = q(1+k), which is a composite number`, `Pump with i = 2`, `Pump with i = 0`, `Pump with i = p`],
    difficulty: 5,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `The original length is q. Pumping i times adds (i-1)k characters. If i = q+1, we add qk characters. Total length q + qk = q(1+k), which is composite since q, k ≥ 1.`,
    keyConcept: `Prime Length Contradiction`,
    commonMistake: ``
  },
  {
    id: 'q_278',
    topicId: 'top_pump_rl_apps',
    text: `Which of the following languages is REGULAR and cannot be proven non-regular with the Pumping Lemma?`,
    correctAnswer: `Strings containing an even number of a's and an odd number of b's`,
    options: [`Strings containing an even number of a's and an odd number of b's`, `Strings with equal numbers of a's and b's`, `Palindromes over {a,b}`, `Strings of the form ww`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Even/odd counting requires a finite number of states (modulo counting). The others require unbounded memory.`,
    keyConcept: `Regular vs Non-Regular`,
    commonMistake: ``
  },
  {
    id: 'q_279',
    topicId: 'top_pump_rl_apps',
    text: `What is the logical deduction if a language L fails the Pumping Lemma (i.e., you find a contradiction)?`,
    correctAnswer: `By Modus Tollens, since regularity implies the pumping property, failing the property implies L is not regular`,
    options: [`By Modus Tollens, since regularity implies the pumping property, failing the property implies L is not regular`, `L must be Context-Free`, `The pumping length p was too small`, `The test is inconclusive`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `If P → Q, then ¬Q → ¬P. This is the logical foundation of the proof.`,
    keyConcept: `Logical Deduction`,
    commonMistake: ``
  },
  {
    id: 'q_280',
    topicId: 'top_pump_rl_apps',
    text: `If pumping UP (i=2) doesn't seem to yield a contradiction for a specific decomposition, what is a valid alternative strategy?`,
    correctAnswer: `Try pumping DOWN (i=0) to see if removing y yields a string outside the language`,
    options: [`Try pumping DOWN (i=0) to see if removing y yields a string outside the language`, `Change the decomposition xyz to a more favorable one`, `Assume the language is regular`, `Increase the pumping length p`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `You only need ONE value of i to fail. Sometimes i=0 (removing the loop) breaks the language constraints when i=2 does not.`,
    keyConcept: `Pumping Down`,
    commonMistake: ``
  },
  {
    id: 'q_281',
    topicId: 'top_closure_rl',
    text: `What does it mathematically mean for the set of Regular Languages to be 'closed' under Union?`,
    correctAnswer: `If L1 and L2 are regular languages, their union (L1 ∪ L2) is guaranteed to be a regular language`,
    options: [`If L1 and L2 are regular languages, their union (L1 ∪ L2) is guaranteed to be a regular language`, `The union of any two languages is finite`, `The DFA for L1 ∪ L2 has no dead states`, `Union removes non-regular strings`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Closure means performing the operation keeps the result inside the same mathematical set (the regular languages).`,
    keyConcept: `Definition of Closure`,
    commonMistake: ``
  },
  {
    id: 'q_282',
    topicId: 'top_closure_rl',
    text: `Are Regular Languages closed under Intersection?`,
    correctAnswer: `Yes, the intersection of two regular languages is always regular`,
    options: [`Yes, the intersection of two regular languages is always regular`, `No, intersection can produce Context-Free Languages`, `Only if the alphabets are identical`, `Only for finite languages`],
    difficulty: 1,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Proved constructively via the Cartesian Product machine or logically via De Morgan's laws.`,
    keyConcept: `Intersection Closure`,
    commonMistake: ``
  },
  {
    id: 'q_283',
    topicId: 'top_closure_rl',
    text: `How is a DFA constructed to prove closure under Complement?`,
    correctAnswer: `Take the DFA for the original language and swap all accept and non-accept states`,
    options: [`Take the DFA for the original language and swap all accept and non-accept states`, `Reverse the direction of all transition arrows`, `Change the start state to an accept state`, `You cannot, it might not be regular`],
    difficulty: 2,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Because a DFA is deterministic and complete, it consumes the entire string. Swapping final states perfectly negates acceptance.`,
    keyConcept: `Complement Construction`,
    commonMistake: ``
  },
  {
    id: 'q_284',
    topicId: 'top_closure_rl',
    text: `If L1 is regular and L2 is non-regular, what can be stated universally about L1 ∩ L2?`,
    correctAnswer: `It could be regular or non-regular depending on the specific languages`,
    options: [`It could be regular or non-regular depending on the specific languages`, `It is always non-regular`, `It is always regular`, `It is always empty`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Example 1: L1=∅ (regular), L1 ∩ L2 = ∅ (regular). Example 2: L1=Σ* (regular), L1 ∩ L2 = L2 (non-regular).`,
    keyConcept: `Mixed Operations`,
    commonMistake: ``
  },
  {
    id: 'q_285',
    topicId: 'top_closure_rl',
    text: `Are Regular Languages closed under the Subset property (i.e., if L is regular, is every subset of L regular)?`,
    correctAnswer: `No`,
    options: [`No`, `Yes`, `Only for infinite subsets`, `Yes, because subsets are smaller`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Σ* is regular. L = {a^n b^n} is a subset of Σ*, but L is NOT regular.`,
    keyConcept: `Subset Non-Closure`,
    commonMistake: ``
  },
  {
    id: 'q_286',
    topicId: 'top_closure_rl',
    text: `Which operation is constructively proven by making the start state final, making final states start, and reversing all transition arrows?`,
    correctAnswer: `Reversal (L^R)`,
    options: [`Reversal (L^R)`, `Complement`, `Intersection`, `Homomorphism`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Reversing the arrows creates an NFA that accepts valid strings from back to front, proving closure under reversal.`,
    keyConcept: `Reversal Construction`,
    commonMistake: ``
  },
  {
    id: 'q_287',
    topicId: 'top_closure_rl',
    text: `How is Closure under Intersection useful in non-regularity proofs?`,
    correctAnswer: `It allows proving a language is non-regular by intersecting it with a known regular language to yield a known non-regular result`,
    options: [`It allows proving a language is non-regular by intersecting it with a known regular language to yield a known non-regular result`, `It minimizes DFAs for faster proofs`, `It generates Regular Expressions`, `It removes ε-transitions`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `If L(unknown) ∩ L(regular) = L(non-regular), then L(unknown) MUST be non-regular. (If it were regular, the intersection would have to be regular).`,
    keyConcept: `Proof Technique`,
    commonMistake: ``
  },
  {
    id: 'q_288',
    topicId: 'top_closure_rl',
    text: `Are Regular Languages closed under Set Difference (L1 - L2)?`,
    correctAnswer: `Yes, because L1 - L2 = L1 ∩ (Complement of L2), and regular languages are closed under both intersection and complement`,
    options: [`Yes, because L1 - L2 = L1 ∩ (Complement of L2), and regular languages are closed under both intersection and complement`, `No, subtraction breaks regularity`, `Yes, but only if L1 is a subset of L2`, `No, unless they are finite`],
    difficulty: 3,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Set difference is derived from intersection and complement, inheriting their closure properties.`,
    keyConcept: `Set Difference`,
    commonMistake: ``
  },
  {
    id: 'q_289',
    topicId: 'top_closure_rl',
    text: `Which of the following operations are Regular Languages NOT closed under?`,
    correctAnswer: `Infinite Union`,
    options: [`Infinite Union`, `Finite Union`, `Kleene Star`, `Homomorphism`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Infinite union can create non-regular languages. For example, the infinite union of {a^n b^n} for every specific n creates a non-regular set from regular single-string sets.`,
    keyConcept: `Infinite Union`,
    commonMistake: ``
  },
  {
    id: 'q_290',
    topicId: 'top_closure_rl',
    text: `If a language consists of all prefixes of strings in a regular language L, is the new language regular?`,
    correctAnswer: `Yes, the prefix closure of a regular language is always regular`,
    options: [`Yes, the prefix closure of a regular language is always regular`, `No, taking prefixes destroys regularity`, `Only if L is finite`, `It depends on the alphabet`],
    difficulty: 4,
    answerMode: 'MULTIPLE_CHOICE',
    type: 'Understanding',
    explanation: `Constructively, take the DFA for L and make every state that has a valid path to a final state into an accept state.`,
    keyConcept: `Prefix Closure`,
    commonMistake: ``
  }
];
