const fs = require('fs');

const questions = [];
let qId = 161;

function addQ(topicId, text, correctAnswer, options, diff, type, expl, conc, mist) {
  questions.push(`  {
    id: 'q_${qId++}',
    topicId: '${topicId}',
    text: \`${text.replace(/\\/g, '\\\\')}\`,
    correctAnswer: \`${correctAnswer.replace(/\\/g, '\\\\')}\`,
    options: [${options.map(o => `\`${o.replace(/\\/g, '\\\\')}\``).join(', ')}],
    difficulty: ${diff},
    answerMode: 'MULTIPLE_CHOICE',
    type: '${type}',
    explanation: \`${expl.replace(/\\/g, '\\\\')}\`,
    keyConcept: \`${conc.replace(/\\/g, '\\\\')}\`,
    commonMistake: \`${mist ? mist.replace(/\\/g, '\\\\') : ''}\`
  }`);
}

function genT(topicId, qs) {
  qs.forEach(q => addQ(topicId, q.t, q.c, q.o, q.d, q.ty || 'Understanding', q.e, q.k, q.m));
}

// 1. top_re_intro
genT('top_re_intro', [
  { t: "What is the primary purpose of a Regular Expression?", c: "To declaratively describe a language using algebraic operations", o: ["To declaratively describe a language using algebraic operations", "To physically process strings with finite memory", "To define context-free grammars", "To simulate a Turing Machine"], d: 1, e: "Regular Expressions are declarative. They specify what the patterns are, rather than the state transitions used to parse them.", k: "Definition of RE" },
  { t: "Which of the following is NOT a fundamental base case in the recursive definition of Regular Expressions?", c: "Any string of length greater than one", o: ["Any string of length greater than one", "The empty set ∅", "The empty string ε", "A single symbol from the alphabet Σ"], d: 2, e: "The base cases are ∅, ε, and single symbols a ∈ Σ. Longer strings are formed by concatenation.", k: "Recursive definition of RE" },
  { t: "Which algebraic operator is NOT part of the standard regular expression definition?", c: "Intersection", o: ["Intersection", "Union (+)", "Concatenation", "Kleene Star (*)"], d: 2, e: "Standard Regular Expressions only use Union, Concatenation, and Kleene Star.", k: "RE operations" },
  { t: "What is the language denoted by the regular expression ∅?", c: "The empty language {}", o: ["The empty language {}", "The language containing the empty string {ε}", "The set of all strings Σ*", "Undefined"], d: 1, e: "∅ denotes a language with no strings. ε denotes a language with one string of length zero.", k: "∅ vs ε" },
  { t: "What is the language denoted by the regular expression ε?", c: "{ε}", o: ["{ε}", "{}", "Σ*", "{∅}"], d: 1, e: "ε represents the language containing exactly one string: the empty string.", k: "∅ vs ε" },
  { t: "If R is a regular expression, what does L(R) represent?", c: "The language described by R", o: ["The language described by R", "The length of R", "The Kleene closure of R", "The reverse of R"], d: 1, e: "L(R) is the standard notation for the language defined by the regular expression R.", k: "Notation" },
  { t: "Which of the following is an RE for the language over {0,1} containing only the exact string '01'?", c: "01", o: ["01", "0+1", "0*1*", "(01)*"], d: 2, e: "Concatenation of '0' and '1' yields exactly the string '01'.", k: "Concatenation" },
  { t: "How does the Kleene Star (*) operator function in a regular expression?", c: "It allows zero or more repetitions of the preceding element", o: ["It allows zero or more repetitions of the preceding element", "It requires exactly one repetition", "It requires one or more repetitions", "It allows zero repetitions only"], d: 1, e: "R* means repeating R 0, 1, 2, or infinite times.", k: "Kleene Star" },
  { t: "If r = a and s = b are REs, what does the RE (r + s) denote?", c: "{a, b}", o: ["{a, b}", "{ab}", "{a, b}*", "{ab, ba}"], d: 2, e: "The union operator (+) combines the strings from both languages.", k: "Union" },
  { t: "What is the difference between R* and R^+ in standard notation?", c: "R* includes zero repetitions (ε), while R^+ requires at least one occurrence of R", o: ["R* includes zero repetitions (ε), while R^+ requires at least one occurrence of R", "R^+ includes ε, while R* does not", "There is no difference", "R^+ allows negative repetitions"], d: 2, e: "R^+ is defined as RR*, ensuring the pattern occurs at least once.", k: "Star vs Plus" }
]);

// 2. top_re_identities
genT('top_re_identities', [
  { t: "Which of the following is the identity element for the Union operation in regular expressions?", c: "∅", o: ["∅", "ε", "Σ*", "The expression itself"], d: 2, e: "R + ∅ = R. Adding the empty language to any language yields the original language.", k: "Identity for Union" },
  { t: "Which of the following is the identity element for Concatenation in regular expressions?", c: "ε", o: ["ε", "∅", "Σ*", "The expression itself"], d: 2, e: "Rε = εR = R. Concatenating the empty string does not change the strings in the language.", k: "Identity for Concatenation" },
  { t: "What is the result of concatenating any regular expression R with the empty set ∅ (i.e., R∅)?", c: "∅", o: ["∅", "R", "ε", "R*"], d: 2, e: "∅ acts as an annihilator for concatenation. You cannot form a string by concatenating from an empty set.", k: "Annihilator for Concatenation" },
  { t: "Which identity represents the Idempotent Law for regular expressions?", c: "R + R = R", o: ["R + R = R", "R* = R", "RS = SR", "R + ∅ = ∅"], d: 2, e: "Set union of a set with itself is the same set: L(R) ∪ L(R) = L(R).", k: "Idempotence" },
  { t: "Does Concatenation distribute over Union?", c: "Yes, R(S + T) = RS + RT", o: ["Yes, R(S + T) = RS + RT", "No", "Only for finite languages", "Yes, R(S + T) = (RS) + T"], d: 3, e: "Concatenation acts like multiplication and distributes over Union (addition).", k: "Distributive Law" },
  { t: "Which identity correctly relates R* and ε?", c: "R* = ε + RR*", o: ["R* = ε + RR*", "R* = εR", "R* = R + ε", "R* = R*R* - ε"], d: 3, e: "R* means 0 repetitions (ε) OR 1 or more repetitions (RR*).", k: "Star Identity" },
  { t: "What is the evaluation of ∅*?", c: "ε", o: ["ε", "∅", "Σ*", "Undefined"], d: 4, e: "Repeating the empty set 0 times gives the empty string ε. Repeating it 1 or more times gives ∅. The union is ε.", k: "Empty set star" },
  { t: "Is (a+b)* equivalent to a* + b*?", c: "No, a* + b* only generates strings of pure a's or pure b's", o: ["No, a* + b* only generates strings of pure a's or pure b's", "Yes, they are identical", "No, (a+b)* cannot generate pure a's", "Yes, by the distributive property"], d: 3, e: "(a+b)* generates mixed strings like 'ab', while a*+b* cannot.", k: "Star over Union" },
  { t: "Which of the following identities is true for the Kleene Star?", c: "(R*)* = R*", o: ["(R*)* = R*", "(R*)* = R", "R* = R", "R* = R + ∅"], d: 3, e: "Applying the star operator multiple times to the same expression does not generate any new strings.", k: "Idempotence of Star" },
  { t: "Which expression is equivalent to (R + S)*?", c: "(R*S*)*", o: ["(R*S*)*", "R* + S*", "R*S*", "R + S*"], d: 4, e: "(R*S*)* allows arbitrary alternations between sequences of R and sequences of S, which exactly matches (R+S)*.", k: "Complex Star Identity" }
]);

// 3. top_fa_and_re
genT('top_fa_and_re', [
  { t: "According to Kleene's Theorem, what is the relationship between Finite Automata and Regular Expressions?", c: "They describe the exact same class of languages", o: ["They describe the exact same class of languages", "FAs describe a larger class of languages", "REs describe a larger class of languages", "They represent different classes of languages"], d: 2, e: "Kleene's theorem formally proves that FAs and REs are exactly equivalent in expressive power.", k: "Kleene's Theorem" },
  { t: "To prove Kleene's Theorem, one must show conversions in both directions. Which conversions are required?", c: "FA to RE, and RE to FA", o: ["FA to RE, and RE to FA", "DFA to NFA, and NFA to DFA", "RE to Context-Free Grammar, and FA to Pushdown Automata", "FA to Turing Machine, and RE to Turing Machine"], d: 2, e: "Equivalence is proven by providing structural algorithms to convert from either model to the other.", k: "Proof Structure" },
  { t: "When converting from a Regular Expression to an Automaton, what type of automaton is typically produced first by standard algorithms like Thompson's Construction?", c: "An NFA with ε-transitions", o: ["An NFA with ε-transitions", "A minimized DFA", "A DFA without ε-transitions", "A Pushdown Automaton"], d: 2, e: "The recursive nature of REs naturally maps to ε-transitions to connect sub-components.", k: "RE to FA Output" },
  { t: "If a language L is recognized by an NFA, can it be described by a Regular Expression?", c: "Yes, because NFAs are equivalent to DFAs, which are equivalent to REs", o: ["Yes, because NFAs are equivalent to DFAs, which are equivalent to REs", "No, NFAs are more powerful", "Only if it has no ε-transitions", "Only if the NFA is minimized"], d: 2, e: "All FA variants (DFA, NFA, ε-NFA) and Regular Expressions describe exactly the Regular Languages.", k: "NFA to RE" },
  { t: "What is the primary significance of proving FAs and REs are equivalent?", c: "It unifies the procedural (FA) and declarative (RE) models of computation", o: ["It unifies the procedural (FA) and declarative (RE) models of computation", "It proves P = NP", "It shows Turing Machines are unnecessary", "It provides a way to minimize REs"], d: 3, e: "It shows that specifying a pattern declaratively is exactly as powerful as building a procedural machine to parse it.", k: "Significance of Equivalence" },
  { t: "Is the set of Regular Languages closed under conversion between REs and FAs?", c: "Yes, they define the exact same set", o: ["Yes, they define the exact same set", "No, converting to RE loses information", "No, FAs can express more", "Yes, but only for finite languages"], d: 1, e: "They are perfectly equivalent definitions of Regular Languages.", k: "Equivalence" },
  { t: "Can a non-regular language be described by a Regular Expression?", c: "No, REs only describe regular languages", o: ["No, REs only describe regular languages", "Yes, using the Kleene star", "Yes, if the expression is infinitely long", "No, unless it uses intersection"], d: 2, e: "By definition, REs describe exactly the regular languages.", k: "Limits of RE" },
  { t: "When an RE is converted to a DFA, is the resulting DFA unique?", c: "No, multiple structurally different DFAs can recognize the same language", o: ["No, multiple structurally different DFAs can recognize the same language", "Yes, the algorithm guarantees a unique DFA", "Yes, but only if the RE has no stars", "No, because DFAs cannot evaluate REs"], d: 2, e: "The specific DFA produced depends on the conversion algorithm. The language is the same, but the machine is not unique until minimized.", k: "Uniqueness" },
  { t: "Which algorithm is commonly used as half of the proof of Kleene's theorem by converting an RE to an FA?", c: "Thompson's Construction", o: ["Thompson's Construction", "Arden's Theorem", "State Elimination", "Subset Construction"], d: 2, e: "Thompson's Construction systematically builds an ε-NFA from a Regular Expression.", k: "Thompson's Construction" },
  { t: "Which method is commonly used as the other half of the proof of Kleene's theorem by converting an FA to an RE?", c: "State Elimination Method", o: ["State Elimination Method", "Subset Construction", "Hopcroft's Algorithm", "Thompson's Construction"], d: 2, e: "State Elimination provides an algorithmic way to extract the Regular Expression from a Finite Automaton.", k: "State Elimination" }
]);

// 4. top_dfa_to_re
genT('top_dfa_to_re', [
  { t: "What is the general solution to the regular expression equation R = Q + RP, according to Arden's Theorem (assuming P does not contain ε)?", c: "R = QP*", o: ["R = QP*", "R = P*Q", "R = Q*P", "R = PQ*"], d: 3, e: "The recursion means R can be Q, QP, QPP, etc., which is algebraically denoted as QP*.", k: "Arden's Theorem" },
  { t: "To apply Arden's theorem uniquely, what condition must hold for R = Q + RP?", c: "P must not contain the empty string ε", o: ["P must not contain the empty string ε", "Q must not contain ε", "R must be empty", "P and Q must be identical"], d: 4, e: "If P contains ε, the equation does not have a unique solution.", k: "Arden's Condition" },
  { t: "In the State Elimination method, what is the first preparatory step?", c: "Add a new start state and a new final state connected via ε-transitions to the original start and final states", o: ["Add a new start state and a new final state connected via ε-transitions to the original start and final states", "Remove all dead states", "Minimize the DFA", "Convert all transitions to Kleene stars"], d: 2, e: "Isolating the start and final states ensures we don't accidentally sever necessary paths when eliminating the original states.", k: "State Elimination Preparation" },
  { t: "When eliminating state q in a path p → q → r, what is the formula for the new direct edge p → r?", c: "(edge p→q) (loop q→q)* (edge q→r)", o: ["(edge p→q) (loop q→q)* (edge q→r)", "(edge p→q) + (edge q→r)", "(edge p→q) (edge q→r)*", "(edge p→r)*"], d: 3, e: "The path must enter q, loop on q any number of times, and then exit q to r.", k: "Elimination Formula" },
  { t: "If there is no self-loop on the state q being eliminated, what does the loop term (q→q)* become in the elimination formula?", c: "ε", o: ["ε", "∅", "It becomes invalid", "It remains as *"], d: 3, e: "If there is no loop, the loop is taken 0 times, which evaluates to ε. The formula simplifies to (edge p→q)(edge q→r).", k: "No loop case" },
  { t: "If eliminating a state creates a new transition p → r, but an edge p → r already exists, what is the correct action?", c: "Label the edge with the Union (+) of the old label and the new label", o: ["Label the edge with the Union (+) of the old label and the new label", "Replace the old edge", "Keep the old edge and discard the new one", "State elimination fails in this case"], d: 3, e: "Parallel paths in an automaton represent a choice, which translates to the Union operator (+).", k: "Parallel Paths" },
  { t: "When do you stop eliminating states in the State Elimination method?", c: "When only the newly added start state and newly added final state remain", o: ["When only the newly added start state and newly added final state remain", "When all loops are removed", "When the DFA becomes an NFA", "When only one original state is left"], d: 2, e: "The final single edge remaining between the new start and new final state contains the complete regular expression.", k: "Termination" },
  { t: "Consider states 1, 2, 3. Edges: 1→2 labeled 'a', 2→2 labeled 'b', 2→3 labeled 'c'. Eliminating state 2 creates what edge from 1 to 3?", c: "ab*c", o: ["ab*c", "a+b*+c", "(abc)*", "a(b+c)*"], d: 3, e: "The path goes in via 'a', loops on 'b' any number of times, and exits via 'c'.", k: "Basic Elimination" },
  { t: "If a state q has incoming edges from states p1, p2 and outgoing edges to states r1, r2, how many new edges are created when q is eliminated?", c: "4", o: ["4", "2", "0", "8"], d: 4, e: "You must connect every incoming node to every outgoing node: p1→r1, p1→r2, p2→r1, p2→r2.", k: "Combinatorial elimination" },
  { t: "If a DFA has no accept states, what is the resulting Regular Expression?", c: "∅", o: ["∅", "ε", "Σ*", "It depends on the start state"], d: 2, e: "No accept states means the DFA accepts nothing, which is the empty language ∅.", k: "Empty DFA" }
]);

// 5. top_re_to_fa
genT('top_re_to_fa', [
  { t: "Which algorithm structurally converts a Regular Expression into an ε-NFA?", c: "Thompson's Construction", o: ["Thompson's Construction", "State Elimination", "Subset Construction", "DFA Minimization"], d: 1, e: "Thompson's algorithm recursively builds an ε-NFA from an RE.", k: "Thompson's Algorithm" },
  { t: "In Thompson's Construction, what does the automaton for a single symbol 'a' look like?", c: "Two states connected by a single transition labeled 'a'", o: ["Two states connected by a single transition labeled 'a'", "One state with a self-loop labeled 'a'", "Three states with ε-transitions", "A single accept state"], d: 2, e: "The base case is simply a start state, a final state, and an edge 'a' between them.", k: "Base Case" },
  { t: "How is Union (R + S) constructed in Thompson's algorithm?", c: "A new start state branches via ε to the starts of R and S, and their finals connect via ε to a new final state", o: ["A new start state branches via ε to the starts of R and S, and their finals connect via ε to a new final state", "Merge the start states of R and S into one", "Connect the final of R to the start of S", "Add a self loop of R+S"], d: 3, e: "Branching with ε-transitions creates the 'OR' choice without consuming input.", k: "Union Construction" },
  { t: "How is Concatenation (RS) constructed in Thompson's algorithm?", c: "Merge the final state of R with the start state of S", o: ["Merge the final state of R with the start state of S", "Add an ε-transition from the start of R to the start of S", "Create a new start state pointing to both", "Connect the final of S to the start of R"], d: 2, e: "When R finishes successfully, it immediately feeds into the beginning of S.", k: "Concatenation Construction" },
  { t: "How many new states are introduced when applying the Kleene Star (R*) in Thompson's construction?", c: "2", o: ["2", "1", "0", "4"], d: 3, e: "A new start and a new final state are added to allow skipping R entirely and cleanly looping back.", k: "Star Construction" },
  { t: "What is a guaranteed property of any ε-NFA generated by Thompson's construction?", c: "It has exactly one start state and one final state", o: ["It has exactly one start state and one final state", "It is deterministic", "It has no ε-transitions", "Every state is an accept state"], d: 3, e: "The construction rules mathematically preserve the invariant of exactly one start and one final state at every recursive step.", k: "Thompson's Properties" },
  { t: "In Thompson's construction for R*, what structural addition allows the expression to evaluate to the empty string ε?", c: "An ε-transition from the newly added start state directly to the newly added final state", o: ["An ε-transition from the newly added start state directly to the newly added final state", "An ε-transition from the old final state to the old start state", "Removing the transitions of R", "Making every state an accept state"], d: 4, e: "This direct ε-transition bypasses the internal machine R entirely, representing zero occurrences.", k: "Star Bypass" },
  { t: "How many states will Thompson's construction produce for the simplest Regular Expression 'a'?", c: "2", o: ["2", "1", "3", "4"], d: 2, e: "A start state, a transition 'a', and a final state.", k: "State Counting" },
  { t: "Is the ε-NFA produced by Thompson's construction the smallest possible automaton for the RE?", c: "No, it often contains many redundant ε-transitions and states", o: ["No, it often contains many redundant ε-transitions and states", "Yes, it is minimal", "Yes, but only for finite languages", "No, but it is always a DFA"], d: 3, e: "Thompson's trades efficiency/minimality for structural simplicity and guaranteed linear construction time.", k: "Minimality" },
  { t: "After generating an ε-NFA using Thompson's construction, how is it typically executed?", c: "By computing the ε-closure of states while processing characters, effectively performing subset construction on the fly", o: ["By computing the ε-closure of states while processing characters, effectively performing subset construction on the fly", "By running it backwards", "By eliminating states", "By using a stack"], d: 4, e: "This approach evaluates the non-deterministic paths deterministically in software.", k: "Execution" }
]);

// 6. top_re_apps
genT('top_re_apps', [
  { t: "Which component of a compiler relies heavily on Regular Expressions?", c: "Lexical Analyzer", o: ["Lexical Analyzer", "Syntax Analyzer", "Semantic Analyzer", "Code Optimizer"], d: 1, e: "Lexical analyzers (scanners) use REs to group characters into meaningful tokens like keywords and identifiers.", k: "Lexical Analysis" },
  { t: "In standard text editors and utilities like grep, what is the primary use of Regular Expressions?", c: "Pattern matching and text search", o: ["Pattern matching and text search", "Syntax highlighting", "Memory management", "File compression"], d: 1, e: "REs are the industry standard for defining search patterns in text processing.", k: "Pattern Matching" },
  { t: "When validating a user's email address on a web form, why are Regular Expressions commonly used?", c: "They succinctly define the specific string structure required for a valid email format", o: ["They succinctly define the specific string structure required for a valid email format", "They encrypt the email address securely", "They connect to a database to verify the user", "They compress the email string"], d: 2, e: "Input validation relies on REs to ensure strings conform to specific structural rules.", k: "Input Validation" },
  { t: "In the context of network security, how are Regular Expressions applied in Intrusion Detection Systems (IDS)?", c: "To define signatures that match known malicious payload patterns in network traffic", o: ["To define signatures that match known malicious payload patterns in network traffic", "To encrypt outgoing packets", "To route packets to the correct IP address", "To allocate bandwidth dynamically"], d: 3, e: "IDS engines scan packet contents against a database of REs representing known attacks.", k: "Network Security" },
  { t: "Can Regular Expressions be used to parse completely nested structures, like matching an arbitrary number of open and closed parentheses in source code?", c: "No, because standard REs cannot count arbitrarily nested structures", o: ["No, because standard REs cannot count arbitrarily nested structures", "Yes, by using the Kleene star", "Yes, but it requires a very long RE", "No, unless they are minimized"], d: 3, e: "Properly nested parentheses form a Context-Free Language, which exceeds the theoretical power of Regular Expressions.", k: "Limitations of REs" },
  { t: "Which UNIX utility is fundamentally built around applying Regular Expressions to extract or transform text line-by-line?", c: "sed", o: ["sed", "ls", "tar", "chmod"], d: 2, e: "sed (stream editor) uses REs to find and replace text patterns.", k: "UNIX Utilities" },
  { t: "In modern programming languages, what does the backslash (\\) typically signify in a Regular Expression string?", c: "An escape character to indicate a literal character or a special character class", o: ["An escape character to indicate a literal character or a special character class", "A division operator", "The end of the regular expression", "A substitution command"], d: 2, e: "Escape characters allow REs to match literals like '*' or '+' that would otherwise act as operators.", k: "Escape Characters" },
  { t: "If a software application needs to extract all phone numbers from a document, what makes a Regular Expression the optimal tool?", c: "It allows searching for a generalized pattern of digits and dashes, rather than searching for specific known numbers", o: ["It allows searching for a generalized pattern of digits and dashes, rather than searching for specific known numbers", "It is faster than a hash map lookup", "It can automatically dial the numbers", "It requires no memory to execute"], d: 2, e: "REs excel at defining generalized patterns (e.g., three digits, a dash, four digits) rather than literal strings.", k: "Generalized Search" },
  { t: "What is a practical limitation of using complex Regular Expressions in production software?", c: "Certain RE patterns can cause catastrophic backtracking, leading to severe performance degradation", o: ["Certain RE patterns can cause catastrophic backtracking, leading to severe performance degradation", "They cannot match uppercase letters", "They take exponential space in memory", "They must be compiled at runtime only"], d: 4, e: "Poorly written REs processed by backtracking engines can exhibit exponential time complexity on specific mismatched strings.", k: "Catastrophic Backtracking" },
  { t: "Why do some modern regex engines (like those in Python or Java) support features like 'backreferences', which are not part of standard mathematical Regular Expressions?", c: "To provide convenience for string manipulation, even though it breaks strict theoretical regularity", o: ["To provide convenience for string manipulation, even though it breaks strict theoretical regularity", "Because backreferences are required by Kleene's Theorem", "To ensure the expressions evaluate in constant time", "To convert them to Pushdown Automata"], d: 4, e: "Practical regex engines extend the mathematical definition to handle non-regular languages (like matching the exact same word twice).", k: "Theory vs Practice" }
]);

// 7. top_rg_def
genT('top_rg_def', [
  { t: "What is the primary function of a Regular Grammar?", c: "To generate exactly the class of Regular Languages", o: ["To generate exactly the class of Regular Languages", "To generate Context-Free Languages", "To parse mathematical equations", "To minimize Finite Automata"], d: 1, e: "Regular Grammars are the generative counterpart to Finite Automata, producing exactly the regular languages.", k: "Function of Regular Grammar" },
  { t: "A formal grammar is defined as a 4-tuple G = (V, T, P, S). What does 'T' represent?", c: "A finite set of terminals", o: ["A finite set of terminals", "The transition function", "A finite set of variables", "The start symbol"], d: 1, e: "T stands for terminals, the actual symbols of the alphabet that make up the final generated strings.", k: "Grammar Tuple" },
  { t: "Which of the following production rule formats is strictly allowed in a Right-Linear Regular Grammar?", c: "A → aB or A → a or A → ε", o: ["A → aB or A → a or A → ε", "A → Ba or A → a or A → ε", "A → aBb", "A → AB"], d: 2, e: "In a right-linear grammar, all non-terminals (variables) must appear strictly at the right end of the production.", k: "Right-Linear Rules" },
  { t: "Which of the following production rule formats is strictly allowed in a Left-Linear Regular Grammar?", c: "A → Ba or A → a or A → ε", o: ["A → Ba or A → a or A → ε", "A → aB or A → a or A → ε", "A → aBb", "A → AB"], d: 2, e: "In a left-linear grammar, all non-terminals (variables) must appear strictly at the left end of the production.", k: "Left-Linear Rules" },
  { t: "If a grammar contains both A → aB (right-linear) and C → Dc (left-linear) production rules, is it guaranteed to be a Regular Grammar?", c: "No, mixing left and right linear rules can generate non-regular languages", o: ["No, mixing left and right linear rules can generate non-regular languages", "Yes, it is still a regular grammar", "Yes, it generates a finite language", "No, because it becomes a Turing Machine"], d: 3, e: "A regular grammar must be strictly right-linear OR strictly left-linear. Mixing them creates a linear grammar, which can generate non-regular languages like a^n b^n.", k: "Mixed Rules" },
  { t: "What does the symbol 'S' represent in the formal definition of a grammar?", c: "The designated start variable", o: ["The designated start variable", "The set of states", "The set of symbols", "A terminal string"], d: 1, e: "S is the start variable (non-terminal) from which all string generation derivations must begin.", k: "Start Symbol" },
  { t: "In a Regular Grammar, what happens when a derivation applies a rule of the form A → a (where 'a' is a terminal)?", c: "The derivation process terminates for that branch because no variables remain", o: ["The derivation process terminates for that branch because no variables remain", "The grammar generates an infinite string", "The grammar returns to the start symbol", "A new variable is created"], d: 2, e: "Terminals cannot be replaced. Without non-terminals remaining, the string generation is complete.", k: "Terminal Derivation" },
  { t: "Which class of grammars in the Chomsky Hierarchy corresponds to Regular Grammars?", c: "Type 3 Grammars", o: ["Type 3 Grammars", "Type 2 Grammars", "Type 1 Grammars", "Type 0 Grammars"], d: 2, e: "In the Chomsky hierarchy, Type 3 grammars are the most restricted class, corresponding to regular languages.", k: "Chomsky Hierarchy" },
  { t: "Can a Regular Grammar generate the empty string ε?", c: "Yes, if there is a production rule of the form A → ε", o: ["Yes, if there is a production rule of the form A → ε", "No, grammars cannot generate empty strings", "Only if the grammar has no variables", "Only in left-linear grammars"], d: 2, e: "The empty string is a valid regular language component, generated via an ε-production.", k: "Empty String Generation" },
  { t: "Why are Regular Grammars computationally equivalent to Finite Automata?", c: "Because the strict linear progression of variables exactly models the state-by-state transitions of an FA", o: ["Because the strict linear progression of variables exactly models the state-by-state transitions of an FA", "Because both use a stack", "Because both are deterministic", "Because Kleene's theorem prohibits variables"], d: 3, e: "Appending a terminal and moving to a new variable maps perfectly to consuming a character and moving to a new state.", k: "Grammar vs FA equivalence" }
]);

// 8. top_rg_and_fa
genT('top_rg_and_fa', [
  { t: "What is the theoretical relationship between Regular Grammars and Finite Automata?", c: "They are completely equivalent; both describe exactly the class of Regular Languages", o: ["They are completely equivalent; both describe exactly the class of Regular Languages", "Finite Automata are more powerful", "Regular Grammars can generate Context-Free Languages", "They are unrelated concepts"], d: 1, e: "Any language generated by a RG can be accepted by an FA, and vice versa.", k: "Equivalence" },
  { t: "When equating a Right-Linear Grammar to a Finite Automaton, what do the non-terminal variables in the grammar represent?", c: "The states of the Finite Automaton", o: ["The states of the Finite Automaton", "The input alphabet", "The transition arrows", "The final accept states"], d: 2, e: "Each variable acts as a state that dictates what symbols can be generated (consumed) next.", k: "Variables as States" },
  { t: "When equating a Right-Linear Grammar to an FA, what does the start variable S represent?", c: "The start state of the automaton", o: ["The start state of the automaton", "The final state of the automaton", "The first character of the string", "The transition function"], d: 2, e: "Both derivation and computation must begin at exactly one designated starting point.", k: "Start State" },
  { t: "In the mapping between a Right-Linear Grammar and an FA, what does a production rule A → aB signify?", c: "A transition from state A to state B labeled with input symbol 'a'", o: ["A transition from state A to state B labeled with input symbol 'a'", "A transition from B to A", "A final state B", "An empty transition"], d: 2, e: "Generating 'a' and moving to 'B' is structurally identical to reading 'a' and transitioning to state B.", k: "Production to Transition" },
  { t: "What does a terminating production rule A → a (or A → ε) signify in the corresponding Finite Automaton?", c: "A transition into a final accept state", o: ["A transition into a final accept state", "A transition back to the start state", "A dead state", "A non-deterministic choice"], d: 3, e: "Terminating the derivation means the string is complete and valid, which corresponds to halting in an accept state.", k: "Terminating Production" },
  { t: "If a Right-Linear Grammar has a rule A → aB and A → aC, what property will the corresponding Finite Automaton exhibit?", c: "Non-determinism (it will be an NFA)", o: ["Non-determinism (it will be an NFA)", "Determinism", "It will reject the string", "It will loop infinitely"], d: 3, e: "Multiple rules for the same variable and terminal mean multiple outgoing transitions for the same symbol from a state, which defines an NFA.", k: "Non-determinism" },
  { t: "Why is a strictly Right-Linear Grammar preferred over a Left-Linear Grammar when mapping directly to standard Finite Automata?", c: "Because FAs process strings from left to right, matching the right-linear generation of appending symbols to the right", o: ["Because FAs process strings from left to right, matching the right-linear generation of appending symbols to the right", "Because Left-Linear Grammars cannot generate regular languages", "Because Left-Linear Grammars are ambiguous", "Because FAs use stacks"], d: 4, e: "Right-linear builds the string left-to-right (a, ab, abc), exactly as an FA reads it.", k: "Right vs Left Linear" },
  { t: "If you convert a Left-Linear Grammar directly to an automaton without reversing it, what does the automaton effectively do?", c: "It processes the string from right to left", o: ["It processes the string from right to left", "It rejects all strings", "It acts as a pushdown automaton", "It loops infinitely"], d: 4, e: "Left-linear grammars build strings by prepending. To parse this directly, the FA would have to read backwards.", k: "Left Linear Execution" },
  { t: "Can a Regular Grammar generate a language that a DFA cannot accept?", c: "No, because every Regular Grammar language is regular, and every regular language has a DFA", o: ["No, because every Regular Grammar language is regular, and every regular language has a DFA", "Yes, if it uses ε-productions", "Yes, if it is non-deterministic", "No, unless it is a Left-Linear grammar"], d: 2, e: "Kleene's theorem and grammar equivalence guarantee DFAs can accept anything a RG generates.", k: "Equivalence Bounds" },
  { t: "In the conversion from RG to FA, is it necessary to create a new, separate final state for rules like A → a?", c: "Yes, it is the standard procedure to ensure the derivation terminates in a valid accept state", o: ["Yes, it is the standard procedure to ensure the derivation terminates in a valid accept state", "No, state A becomes the final state", "No, the start state becomes final", "Yes, but only if 'a' is ε"], d: 3, e: "A rule A → a implies generating 'a' and stopping. In the FA, this means from state A, read 'a' and go to an accept state.", k: "Final State Creation" }
]);

// 9. top_fa_to_rg
genT('top_fa_to_rg', [
  { t: "When converting a DFA to a Right-Linear Grammar, what does each state of the DFA become?", c: "A variable (non-terminal) in the grammar", o: ["A variable (non-terminal) in the grammar", "A production rule", "A terminal symbol", "The start symbol"], d: 1, e: "States map directly to non-terminal variables representing the current condition of the generation.", k: "State mapping" },
  { t: "Given a transition δ(q1, a) = q2 in a DFA, what production rule is added to the corresponding Right-Linear Grammar?", c: "q1 → a q2", o: ["q1 → a q2", "q2 → a q1", "q1 → q2 a", "q1 → a"], d: 2, e: "Being in state q1 and reading 'a' to reach q2 translates to variable q1 generating 'a' and becoming variable q2.", k: "Transition mapping" },
  { t: "If a state q_f is a final (accept) state in the DFA, what production rule must be added for its corresponding variable?", c: "q_f → ε", o: ["q_f → ε", "q_f → a", "q_f → q_f", "No rule is added"], d: 2, e: "Accepting a string means the generation can halt at this point without generating any more characters.", k: "Final state mapping" },
  { t: "Consider a DFA with a start state q0. What becomes the start symbol of the generated grammar?", c: "q0", o: ["q0", "A new variable S", "ε", "The final state"], d: 1, e: "Generation must begin exactly where the DFA begins reading the string.", k: "Start symbol mapping" },
  { t: "If a DFA transition is δ(q1, a) = q2, and q2 is a final state, which of the following alternative production rules can be added to bypass creating ε-rules?", c: "q1 → a", o: ["q1 → a", "q2 → a", "q1 → ε", "q2 → a q1"], d: 3, e: "If moving to q2 means the string can be accepted, then q1 can just generate 'a' and terminate the derivation.", k: "Alternative termination" },
  { t: "Does converting a DFA to a Regular Grammar preserve determinism in the grammatical structure?", c: "Yes, for any variable A and terminal a, there will be at most one rule A → aB", o: ["Yes, for any variable A and terminal a, there will be at most one rule A → aB", "No, the resulting grammar is always ambiguous", "No, grammars have no concept related to determinism", "Yes, but only if the DFA is minimized"], d: 4, e: "Because a DFA has exactly one transition for a given state and symbol, the grammar will have exactly one matching production.", k: "Determinism preservation" },
  { t: "Convert this DFA segment to a grammar rule: From state A, upon reading '0', loop back to state A.", c: "A → 0 A", o: ["A → 0 A", "A → A 0", "A → 0", "0 → A 0"], d: 2, e: "The variable A generates a '0' and remains variable A.", k: "Loop mapping" },
  { t: "If the start state of an FA is also a final state, what rule will appear in the grammar?", c: "S → ε (where S is the start variable)", o: ["S → ε (where S is the start variable)", "S → S", "S → ∅", "No special rule is needed"], d: 2, e: "If the start state is final, the FA accepts the empty string, so the grammar must be able to generate it immediately.", k: "Start state as final" },
  { t: "Can this conversion algorithm be applied to an NFA as well as a DFA?", c: "Yes, the exact same rules apply, resulting in a Right-Linear Grammar", o: ["Yes, the exact same rules apply, resulting in a Right-Linear Grammar", "No, NFAs must be converted to DFAs first", "Only if the NFA has no ε-transitions", "No, NFAs result in Context-Free Grammars"], d: 3, e: "Multiple transitions for the same symbol in an NFA simply result in multiple production rules (e.g., A → aB and A → aC), which is perfectly valid.", k: "NFA application" },
  { t: "What happens to 'dead states' (states that cannot reach a final state) during conversion?", c: "They generate variables with production rules, but derivations entering these variables can never terminate into purely terminal strings", o: ["They generate variables with production rules, but derivations entering these variables can never terminate into purely terminal strings", "They are automatically ignored", "They generate ε-productions", "They cause the grammar to be invalid"], d: 4, e: "The rules exist, but since there is no path to a final state, there is no path to an A → ε rule, meaning the derivation never finishes.", k: "Dead states" }
]);

// 10. top_rg_to_fa
genT('top_rg_to_fa', [
  { t: "When converting a Right-Linear Grammar to an FA, what is the first structural step?", c: "Create a state for every variable, plus one special new final state", o: ["Create a state for every variable, plus one special new final state", "Create a state for every terminal", "Create a single start state", "Minimize the grammar"], d: 2, e: "Variables become states. The special final state is needed as a destination for terminating rules like A → a.", k: "Initial setup" },
  { t: "Given a production rule A → bC in the grammar, what transition is added to the FA?", c: "A transition from state A to state C labeled 'b'", o: ["A transition from state A to state C labeled 'b'", "A transition from C to A labeled 'b'", "A transition from A to C labeled 'C'", "A transition from start to A labeled 'b'"], d: 2, e: "The variable A generates 'b' and becomes C, mapping to transitioning from state A to C on input 'b'.", k: "Production mapping" },
  { t: "Given a terminating production rule A → c in the grammar, what transition is added to the FA?", c: "A transition from state A to the special final state labeled 'c'", o: ["A transition from state A to the special final state labeled 'c'", "A transition from state A to itself labeled 'c'", "An ε-transition to state c", "A transition from the start state to A"], d: 3, e: "The derivation halts upon generating 'c', so the FA must transition to an accept state upon reading 'c'.", k: "Terminating rule mapping" },
  { t: "If a grammar contains the rule A → ε, what happens to state A in the resulting FA?", c: "State A is marked as a final (accept) state", o: ["State A is marked as a final (accept) state", "An ε-transition is drawn to the start state", "State A is deleted", "An ε-transition is drawn to the special final state"], d: 3, e: "Generating ε means the derivation can successfully halt at A, making A an accept state.", k: "Epsilon rule mapping" },
  { t: "What type of automaton is typically produced by the direct conversion of a Regular Grammar to an FA?", c: "An NFA", o: ["An NFA", "A minimal DFA", "A Pushdown Automaton", "A DFA"], d: 3, e: "Grammars naturally contain non-determinism (e.g., A → bC and A → bD), which maps directly to an NFA.", k: "Resulting machine type" },
  { t: "If the start variable of the grammar is S, what is the start state of the FA?", c: "The state corresponding to variable S", o: ["The state corresponding to variable S", "The special final state", "A newly created empty state", "Any state with an outgoing transition"], d: 1, e: "The derivation begins at S, so the computation must begin at state S.", k: "Start state mapping" },
  { t: "Consider a grammar with rules S → 0A, A → 1. How many states does the resulting FA have?", c: "3", o: ["3", "2", "4", "1"], d: 4, e: "State S, state A, and the special final state (for the A → 1 rule).", k: "State count calculation" },
  { t: "Why is a special final state necessary when converting RG to FA?", c: "To provide a destination state for terminating rules of the form A → a", o: ["To provide a destination state for terminating rules of the form A → a", "To make the machine deterministic", "To handle ε-productions", "To prevent infinite loops"], d: 3, e: "A transition requires a destination. A → a means 'consume a and accept'. The special final state acts as that accepting destination.", k: "Purpose of special final state" },
  { t: "If a Right-Linear Grammar has multiple rules for the same variable and terminal (e.g., A → 0B, A → 0C), what happens in the FA?", c: "State A will have multiple outgoing transitions on '0', making it an NFA", o: ["State A will have multiple outgoing transitions on '0', making it an NFA", "The conversion fails", "One rule is ignored", "A new terminal is created"], d: 3, e: "This directly translates to non-deterministic branching in the automaton.", k: "Non-determinism mapping" },
  { t: "Can this conversion be used for Left-Linear Grammars directly to yield a standard left-to-right FA?", c: "No, converting Left-Linear directly yields an FA that reads strings backwards", o: ["No, converting Left-Linear directly yields an FA that reads strings backwards", "Yes, it works identically", "No, Left-Linear grammars cannot be converted to FAs", "Yes, but the FA must be deterministic"], d: 4, e: "Left-linear grammars build strings by prepending. To get a standard left-to-right FA, one must reverse the grammar, apply the right-linear algorithm, and then reverse the resulting NFA.", k: "Left-linear conversion" }
]);

// 11. top_pump_rl
genT('top_pump_rl', [
  { t: "What is the formal purpose of the Pumping Lemma for Regular Languages?", c: "To prove that a specific language is NOT regular by contradiction", o: ["To prove that a specific language is NOT regular by contradiction", "To prove that a language IS regular", "To convert an NFA to a DFA", "To minimize a Finite Automaton"], d: 1, e: "It provides a necessary condition for regularity. Failing the condition proves non-regularity.", k: "Purpose of Pumping Lemma" },
  { t: "In the formal statement of the Pumping Lemma, for a regular language L, what is 'p'?", c: "A constant integer ≥ 1 known as the pumping length, which depends only on L", o: ["A constant integer ≥ 1 known as the pumping length, which depends only on L", "The length of the chosen string s", "The number of times the string is pumped", "The number of non-terminals in the grammar"], d: 2, e: "The pumping length p represents (conceptually) the number of states in the DFA that recognizes L.", k: "Pumping length p" },
  { t: "In the Pumping Lemma, the string s is decomposed into s = xyz. What condition restricts the length of the substring 'y'?", c: "|y| > 0", o: ["|y| > 0", "|y| ≥ 0", "|y| = p", "|y| < p"], d: 2, e: "The substring y (the loop) must contain at least one character, otherwise pumping it has no effect.", k: "Condition: |y| > 0" },
  { t: "What condition restricts the position of the substring 'y' in the Pumping Lemma?", c: "|xy| ≤ p", o: ["|xy| ≤ p", "|xy| > p", "|xy| = 0", "|xy| ≥ p"], d: 3, e: "By the Pigeonhole Principle, the first repetition of a state (the loop) must occur within the first p characters.", k: "Condition: |xy| <= p" },
  { t: "What does the Pumping Lemma state must be true for all i ≥ 0?", c: "xy^iz ∈ L", o: ["xy^iz ∈ L", "xy^iz ∉ L", "x^iyz ∈ L", "xyz^i ∈ L"], d: 2, e: "If you repeat the loop substring 'y' any number of times (i), the resulting string must still be in the language.", k: "Pumping condition" },
  { t: "In a formal proof using the Pumping Lemma, who chooses the string 's'?", c: "The prover chooses s, but it must be in L and satisfy |s| ≥ p", o: ["The prover chooses s, but it must be in L and satisfy |s| ≥ p", "The adversary chooses s", "s is always fixed as a^p b^p", "s is randomly generated"], d: 4, e: "You (the prover) select a strategic string s to force the adversary's decomposition into an unavoidable contradiction.", k: "Quantifiers: Choosing s" },
  { t: "In a formal proof using the Pumping Lemma, who chooses the decomposition s = xyz?", c: "The adversary chooses the decomposition; the proof must hold for ALL valid decompositions", o: ["The adversary chooses the decomposition; the proof must hold for ALL valid decompositions", "The prover chooses the most convenient decomposition", "The decomposition is always x=ε, y=s, z=ε", "The decomposition is random"], d: 5, e: "This is the most critical quantifier trap. You cannot assume y is a specific substring; you must prove the contradiction occurs for ANY valid xyz.", k: "Quantifiers: Choosing xyz" },
  { t: "If you choose to pump with i = 0 (yielding xz), what does this conceptually represent in the DFA?", c: "Bypassing the loop entirely", o: ["Bypassing the loop entirely", "Traversing the loop backwards", "Going to a dead state", "Rejecting the string"], d: 3, e: "Since y is the loop, repeating it 0 times means you take the path that skips the loop.", k: "Pumping down" },
  { t: "What mathematical principle guarantees the existence of the loop 'y'?", c: "The Pigeonhole Principle", o: ["The Pigeonhole Principle", "Mathematical Induction", "De Morgan's Laws", "The Halting Problem"], d: 2, e: "If a path processes p characters, it visits p+1 states. If the DFA has only p states, at least one state must be visited twice.", k: "Pigeonhole Principle" },
  { t: "If a language satisfies all conditions of the Pumping Lemma, is it definitely regular?", c: "No, there are non-regular languages that satisfy the Pumping Lemma", o: ["No, there are non-regular languages that satisfy the Pumping Lemma", "Yes, it is a sufficient condition", "Yes, but only if the alphabet is binary", "No, it must be a Context-Free language"], d: 4, e: "The lemma is a necessary condition, but not a sufficient one. (e.g., L = {a^i b^j c^k | i,j,k ≥ 0 and if i=1 then j=k} is non-regular but pumps).", k: "Necessary vs Sufficient" }
]);

// 12. top_pump_rl_apps
genT('top_pump_rl_apps', [
  { t: "When proving L = {a^n b^n | n ≥ 0} is not regular, what is the strategically best choice for the string s?", c: "s = a^p b^p", o: ["s = a^p b^p", "s = a b", "s = a^n b^n", "s = a^p"], d: 3, e: "Choosing a^p b^p forces the first p characters to be entirely 'a's, ensuring that the substring 'y' must consist solely of 'a's.", k: "Strategic Choice of s" },
  { t: "For L = {a^n b^n}, if s = a^p b^p, what does the condition |xy| ≤ p logically enforce?", c: "The substring 'y' consists entirely of 'a's", o: ["The substring 'y' consists entirely of 'a's", "The substring 'y' consists entirely of 'b's", "The substring 'y' crosses the boundary between a and b", "The substring 'y' is empty"], d: 3, e: "Since xy is at most length p, and the first p characters are all 'a's, y cannot contain any 'b's.", k: "Forcing y's composition" },
  { t: "In the proof for L = {a^n b^n}, after determining y is only 'a's, what happens when you pump with i=2?", c: "The number of 'a's increases while the number of 'b's remains unchanged, violating the n=n condition", o: ["The number of 'a's increases while the number of 'b's remains unchanged, violating the n=n condition", "The number of 'b's increases", "The string remains in L", "The string becomes empty"], d: 2, e: "The resulting string has p+|y| 'a's and p 'b's. Since |y| > 0, they are no longer equal.", k: "Deriving the contradiction" },
  { t: "Why is the informal rule 'Finite Automata cannot count' slightly inaccurate?", c: "Finite Automata can count up to a fixed, finite maximum (like modulo counting); they only fail at unbounded counting", o: ["Finite Automata can count up to a fixed, finite maximum (like modulo counting); they only fail at unbounded counting", "Finite Automata can count infinitely", "Finite Automata cannot count at all", "Only Pushdown Automata can count modulo"], d: 3, e: "A DFA can easily accept 'strings with exactly 5 a's' or 'even length strings'. It fails on unbounded parity requirements like a^n b^n.", k: "Unbounded Counting" },
  { t: "When proving L = {ww | w ∈ {a,b}*} is not regular, what is a strong adversarial choice for s?", c: "s = a^p b a^p b", o: ["s = a^p b a^p b", "s = a^p a^p", "s = a b a b", "s = w w"], d: 5, e: "Choosing a^p b a^p b forces y to be entirely 'a's in the first half. Pumping it imbalances the symmetry between the two halves.", k: "Advanced Choice of s" },
  { t: "If you attempt to prove L = {a^n b^n} is non-regular by choosing s = a^(p/2) b^(p/2), what complication arises?", c: "The substring y might contain a mix of 'a's and 'b's, requiring you to analyze multiple complex cases", o: ["The substring y might contain a mix of 'a's and 'b's, requiring you to analyze multiple complex cases", "The length of s is less than p", "The string is not in L", "You cannot pump a mixed string"], d: 4, e: "If |xy| ≤ p crosses the midpoint, y could be a^j, b^k, or a^j b^k. You must prove ALL cases fail, making the proof unnecessarily difficult.", k: "Poor Choice of s" },
  { t: "Prove L = {a^p | p is prime} is not regular. After choosing s = a^q (where q is prime ≥ p), what is a valid contradiction strategy for pumping y (length k)?", c: "Pump with i = q + 1, making the new length q + qk = q(1+k), which is a composite number", o: ["Pump with i = q + 1, making the new length q + qk = q(1+k), which is a composite number", "Pump with i = 2", "Pump with i = 0", "Pump with i = p"], d: 5, e: "The original length is q. Pumping i times adds (i-1)k characters. If i = q+1, we add qk characters. Total length q + qk = q(1+k), which is composite since q, k ≥ 1.", k: "Prime Length Contradiction" },
  { t: "Which of the following languages is REGULAR and cannot be proven non-regular with the Pumping Lemma?", c: "Strings containing an even number of a's and an odd number of b's", o: ["Strings containing an even number of a's and an odd number of b's", "Strings with equal numbers of a's and b's", "Palindromes over {a,b}", "Strings of the form ww"], d: 2, e: "Even/odd counting requires a finite number of states (modulo counting). The others require unbounded memory.", k: "Regular vs Non-Regular" },
  { t: "What is the logical deduction if a language L fails the Pumping Lemma (i.e., you find a contradiction)?", c: "By Modus Tollens, since regularity implies the pumping property, failing the property implies L is not regular", o: ["By Modus Tollens, since regularity implies the pumping property, failing the property implies L is not regular", "L must be Context-Free", "The pumping length p was too small", "The test is inconclusive"], d: 3, e: "If P → Q, then ¬Q → ¬P. This is the logical foundation of the proof.", k: "Logical Deduction" },
  { t: "If pumping UP (i=2) doesn't seem to yield a contradiction for a specific decomposition, what is a valid alternative strategy?", c: "Try pumping DOWN (i=0) to see if removing y yields a string outside the language", o: ["Try pumping DOWN (i=0) to see if removing y yields a string outside the language", "Change the decomposition xyz to a more favorable one", "Assume the language is regular", "Increase the pumping length p"], d: 4, e: "You only need ONE value of i to fail. Sometimes i=0 (removing the loop) breaks the language constraints when i=2 does not.", k: "Pumping Down" }
]);

// 13. top_closure_rl
genT('top_closure_rl', [
  { t: "What does it mathematically mean for the set of Regular Languages to be 'closed' under Union?", c: "If L1 and L2 are regular languages, their union (L1 ∪ L2) is guaranteed to be a regular language", o: ["If L1 and L2 are regular languages, their union (L1 ∪ L2) is guaranteed to be a regular language", "The union of any two languages is finite", "The DFA for L1 ∪ L2 has no dead states", "Union removes non-regular strings"], d: 1, e: "Closure means performing the operation keeps the result inside the same mathematical set (the regular languages).", k: "Definition of Closure" },
  { t: "Are Regular Languages closed under Intersection?", c: "Yes, the intersection of two regular languages is always regular", o: ["Yes, the intersection of two regular languages is always regular", "No, intersection can produce Context-Free Languages", "Only if the alphabets are identical", "Only for finite languages"], d: 1, e: "Proved constructively via the Cartesian Product machine or logically via De Morgan's laws.", k: "Intersection Closure" },
  { t: "How is a DFA constructed to prove closure under Complement?", c: "Take the DFA for the original language and swap all accept and non-accept states", o: ["Take the DFA for the original language and swap all accept and non-accept states", "Reverse the direction of all transition arrows", "Change the start state to an accept state", "You cannot, it might not be regular"], d: 2, e: "Because a DFA is deterministic and complete, it consumes the entire string. Swapping final states perfectly negates acceptance.", k: "Complement Construction" },
  { t: "If L1 is regular and L2 is non-regular, what can be stated universally about L1 ∩ L2?", c: "It could be regular or non-regular depending on the specific languages", o: ["It could be regular or non-regular depending on the specific languages", "It is always non-regular", "It is always regular", "It is always empty"], d: 4, e: "Example 1: L1=∅ (regular), L1 ∩ L2 = ∅ (regular). Example 2: L1=Σ* (regular), L1 ∩ L2 = L2 (non-regular).", k: "Mixed Operations" },
  { t: "Are Regular Languages closed under the Subset property (i.e., if L is regular, is every subset of L regular)?", c: "No", o: ["No", "Yes", "Only for infinite subsets", "Yes, because subsets are smaller"], d: 3, e: "Σ* is regular. L = {a^n b^n} is a subset of Σ*, but L is NOT regular.", k: "Subset Non-Closure" },
  { t: "Which operation is constructively proven by making the start state final, making final states start, and reversing all transition arrows?", c: "Reversal (L^R)", o: ["Reversal (L^R)", "Complement", "Intersection", "Homomorphism"], d: 3, e: "Reversing the arrows creates an NFA that accepts valid strings from back to front, proving closure under reversal.", k: "Reversal Construction" },
  { t: "How is Closure under Intersection useful in non-regularity proofs?", c: "It allows proving a language is non-regular by intersecting it with a known regular language to yield a known non-regular result", o: ["It allows proving a language is non-regular by intersecting it with a known regular language to yield a known non-regular result", "It minimizes DFAs for faster proofs", "It generates Regular Expressions", "It removes ε-transitions"], d: 4, e: "If L(unknown) ∩ L(regular) = L(non-regular), then L(unknown) MUST be non-regular. (If it were regular, the intersection would have to be regular).", k: "Proof Technique" },
  { t: "Are Regular Languages closed under Set Difference (L1 - L2)?", c: "Yes, because L1 - L2 = L1 ∩ (Complement of L2), and regular languages are closed under both intersection and complement", o: ["Yes, because L1 - L2 = L1 ∩ (Complement of L2), and regular languages are closed under both intersection and complement", "No, subtraction breaks regularity", "Yes, but only if L1 is a subset of L2", "No, unless they are finite"], d: 3, e: "Set difference is derived from intersection and complement, inheriting their closure properties.", k: "Set Difference" },
  { t: "Which of the following operations are Regular Languages NOT closed under?", c: "Infinite Union", o: ["Infinite Union", "Finite Union", "Kleene Star", "Homomorphism"], d: 4, e: "Infinite union can create non-regular languages. For example, the infinite union of {a^n b^n} for every specific n creates a non-regular set from regular single-string sets.", k: "Infinite Union" },
  { t: "If a language consists of all prefixes of strings in a regular language L, is the new language regular?", c: "Yes, the prefix closure of a regular language is always regular", o: ["Yes, the prefix closure of a regular language is always regular", "No, taking prefixes destroys regularity", "Only if L is finite", "It depends on the alphabet"], d: 4, e: "Constructively, take the DFA for L and make every state that has a valid path to a final state into an accept state.", k: "Prefix Closure" }
]);

const content = `import { Question } from '../../types';\n\nexport const MODULE_2_QUESTIONS: Question[] = [\n${questions.join(',\n')}\n];\n`;
fs.writeFileSync('src/lib/content/questions2.ts', content);
