const fs = require('fs');

const questions = [];
let qId = 161;

function addQ(topicId, text, correctAnswer, options, diff, type, expl, conc, mist) {
  questions.push(`  {
    id: 'q_${qId++}',
    topicId: '${topicId}',
    text: \`${text.replace(/\\/g, '\\\\')}\`,
    correctAnswer: \`${correctAnswer.replace(/\\/g, '\\\\')}\`,
    options: [${options.map(o => `\`${o.replace(/\\/g, '\\\\')}\``).join(', ')}],
    difficulty: ${diff},
    answerMode: 'MULTIPLE_CHOICE',
    type: '${type}',
    explanation: \`${expl.replace(/\\/g, '\\\\')}\`,
    keyConcept: \`${conc.replace(/\\/g, '\\\\')}\`,
    commonMistake: \`${mist ? mist.replace(/\\/g, '\\\\') : ''}\`
  }`);
}

// Helper to generate Qs for a topic
function genT(topicId, qs) {
  qs.forEach(q => addQ(topicId, q.t, q.c, q.o, q.d, q.ty || 'Understanding', q.e, q.k, q.m));
}

// 1. top_re_intro
genT('top_re_intro', [
  { t: "What is the primary purpose of a Regular Expression?", c: "To declaratively describe a language using algebraic operations", o: ["To declaratively describe a language using algebraic operations", "To physically process strings with finite memory", "To define context-free grammars", "To simulate a Turing Machine"], d: 1, e: "REs are declarative/algebraic, while FAs are computational/state-based models of regular languages.", k: "Definition of RE" },
  { t: "Which of the following is NOT a fundamental base case in the recursive definition of Regular Expressions?", c: "Any string over Σ", o: ["Any string over Σ", "The empty set ∅", "The empty string ε", "A single symbol from Σ"], d: 2, e: "The base cases are ∅, ε, and a ∈ Σ. A string of length > 1 is formed by concatenating base cases.", k: "Recursive definition of RE" },
  { t: "Which algebraic operator is NOT part of the standard regular expression definition?", c: "Intersection", o: ["Intersection", "Union (+)", "Concatenation", "Kleene Star (*)"], d: 2, e: "While regular languages are closed under intersection, standard REs only use Union, Concatenation, and Kleene Star.", k: "RE operations" },
  { t: "What is the language denoted by the regular expression ∅?", c: "The empty language {}", o: ["The empty language {}", "The language containing the empty string {ε}", "The set of all strings Σ*", "Undefined"], d: 1, e: "∅ denotes a language with no strings. ε denotes a language with one string of length zero.", k: "∅ vs ε" },
  { t: "What is the language denoted by the regular expression ε?", c: "{ε}", o: ["{ε}", "{}", "Σ*", "{∅}"], d: 1, e: "ε represents the language containing exactly one string: the empty string.", k: "∅ vs ε" },
  { t: "If R is a regular expression, what does L(R) represent?", c: "The language described by R", o: ["The language described by R", "The length of R", "The Kleene closure of R", "The reverse of R"], d: 1, e: "L(R) is the standard notation for the language defined by the regular expression R.", k: "Notation" },
  { t: "Which of the following is an RE for the language over {0,1} containing only the string '01'?", c: "01", o: ["01", "0+1", "0*1*", "(01)*"], d: 2, e: "Concatenation of '0' and '1' yields exactly the string '01'.", k: "Concatenation" },
  { t: "What is the relation between Regular Expressions and Finite Automata?", c: "They describe the exact same class of languages", o: ["They describe the exact same class of languages", "REs describe a larger class of languages", "FAs describe a larger class of languages", "They are unrelated"], d: 2, e: "Kleene's theorem proves they both describe exactly the Regular Languages.", k: "Kleene's Theorem" },
  { t: "If r = a and s = b are REs, what does the RE (r + s) denote?", c: "{a, b}", o: ["{a, b}", "{ab}", "{a, b}*", "{ab, ba}"], d: 2, e: "The union operator (+) combines the strings from both languages.", k: "Union" },
  { t: "Which of the following describes the declarative nature of REs?", c: "It specifies what patterns strings must have, rather than how to parse them", o: ["It specifies what patterns strings must have, rather than how to parse them", "It reads strings character by character and updates states", "It uses a stack to match brackets", "It requires unbounded memory"], d: 2, e: "Declarative means specifying 'what' rather than 'how'. FAs are procedural/how.", k: "Declarative property" }
]);

// 2. top_re_operators
genT('top_re_operators', [
  { t: "What does the Kleene Star (*) operator represent in a regular expression?", c: "Zero or more repetitions of the preceding element", o: ["Zero or more repetitions of the preceding element", "Exactly one repetition", "One or more repetitions", "Zero repetitions"], d: 1, e: "R* means repeating R 0, 1, 2, ... infinite times.", k: "Kleene Star" },
  { t: "What is the difference between R* and R^+?", c: "R* includes ε, while R^+ requires at least one occurrence of R", o: ["R* includes ε, while R^+ requires at least one occurrence of R", "R^+ includes ε, while R* does not", "There is no difference", "R^+ allows negative repetitions"], d: 2, e: "R^+ = RR*, ensuring the pattern occurs at least once.", k: "Star vs Plus" },
  { t: "How is the Union operator typically denoted in regular expressions?", c: "+ or |", o: ["+ or |", "*", "&", "^"], d: 1, e: "Union is written as + or | (e.g., a+b or a|b).", k: "Union notation" },
  { t: "What is the language of the regular expression (0+1)*?", c: "All possible strings over {0,1}", o: ["All possible strings over {0,1}", "Only strings of alternating 0s and 1s", "Only strings of all 0s or all 1s", "The empty string"], d: 2, e: "(0+1) is any single bit. Star allows choosing any single bit any number of times.", k: "Universal Language" },
  { t: "If L(R) = {a} and L(S) = {b}, what is L(RS)?", c: "{ab}", o: ["{ab}", "{a, b}", "{ba}", "{a, b, ab}"], d: 2, e: "Concatenation combines each string from the first set with each string from the second set.", k: "Concatenation" },
  { t: "What does the expression a*b* mean?", c: "Any number of a's followed by any number of b's", o: ["Any number of a's followed by any number of b's", "Any string of a's and b's", "Same number of a's and b's", "An 'a' followed by a 'b', repeated any number of times"], d: 2, e: "a* generates a's, b* generates b's. Concatenation means a's happen first, then b's.", k: "Concatenation and Star" },
  { t: "Which equation is universally true for regular expressions?", c: "R + R = R", o: ["R + R = R", "R* = R", "RS = SR", "R + ∅ = ∅"], d: 3, e: "Set union of a set with itself is the same set. L(R) ∪ L(R) = L(R).", k: "Idempotence" },
  { t: "Which identity correctly relates R* and ε?", c: "R* = ε + RR*", o: ["R* = ε + RR*", "R* = εR", "R* = R + ε", "R* = R*R* - ε"], d: 3, e: "R* means 0 repetitions (ε) OR 1 or more repetitions (RR*).", k: "Star Identity" },
  { t: "What is the evaluation of ∅*?", c: "{ε}", o: ["{ε}", "{}", "∅", "Σ*"], d: 4, e: "Repeating the empty set 0 times gives the empty string ε. Repeating it >0 times gives ∅. Union is {ε}.", k: "Empty set star" },
  { t: "What is the evaluation of R ∅?", c: "∅", o: ["∅", "R", "R*", "{ε}"], d: 3, e: "Concatenating anything with the empty set yields the empty set.", k: "Annihilator" }
]);

// 3. top_re_precedence
genT('top_re_precedence', [
  { t: "In the absence of parentheses, what is the operator precedence in Regular Expressions from highest to lowest?", c: "Star, Concatenation, Union", o: ["Star, Concatenation, Union", "Union, Concatenation, Star", "Concatenation, Star, Union", "Star, Union, Concatenation"], d: 1, e: "Star is like an exponent, Concatenation is like multiplication, Union is like addition.", k: "Precedence Rules" },
  { t: "How is the regular expression 01* evaluated?", c: "0(1*)", o: ["0(1*)", "(01)*", "(0*1)*", "0*(1*)"], d: 2, e: "Star has highest precedence, so it only applies to the immediately preceding character '1'.", k: "Precedence Application" },
  { t: "Which expression is equivalent to a + bc*?", c: "a + (b(c*))", o: ["a + (b(c*))", "(a + b)c*", "((a + b)c)*", "a + ((bc)*)"], d: 2, e: "c* binds first, then b concatenates with c*, then union with a.", k: "Precedence Application" },
  { t: "If you want to apply the Kleene Star to the string 'ab', how must you write it?", c: "(ab)*", o: ["(ab)*", "ab*", "a*b*", "[ab]*"], d: 1, e: "Parentheses are required to override the default precedence where * only binds to 'b'.", k: "Overriding Precedence" },
  { t: "What language does 0+10* denote?", c: "{0} ∪ {1, 10, 100, ...}", o: ["{0} ∪ {1, 10, 100, ...}", "{0, 1, 00, 10, ...}", "All strings ending in 0", "All strings starting with 0 or 1"], d: 3, e: "Evaluated as 0 + (1(0*)). It accepts '0' OR '1' followed by any number of '0's.", k: "Evaluation" },
  { t: "Which of the following expressions are equivalent?", c: "(a+b)* and (a*b*)*", o: ["(a+b)* and (a*b*)*", "ab* and (ab)*", "a+b* and (a+b)*", "a*+b* and (a+b)*"], d: 4, e: "Both generate all possible strings over {a,b}. (a*b*)* allows alternating a's and b's.", k: "Equivalence" },
  { t: "What is the equivalent fully parenthesized form of a*+b?", c: "((a*) + b)", o: ["((a*) + b)", "(a*(+b))", "(a(*+b))", "(a*)+b*"], d: 2, e: "Star applies to a, then Union applies to the result and b.", k: "Parenthesization" },
  { t: "Why is operator precedence important in Regular Expressions?", c: "To remove ambiguity without needing excessive parentheses", o: ["To remove ambiguity without needing excessive parentheses", "To make the machines run faster", "To reduce the number of states in a DFA", "To comply with Kleene's theorem"], d: 2, e: "Precedence rules act as syntax conventions to keep REs readable.", k: "Purpose of Precedence" },
  { t: "Does Concatenation distribute over Union?", c: "Yes, a(b+c) = ab + ac", o: ["Yes, a(b+c) = ab + ac", "No", "Only for finite languages", "Yes, a(b+c) = (ab)+c"], d: 3, e: "Concatenation acts like multiplication and distributes over Union (addition).", k: "Distributive Law" },
  { t: "Is (a+b)* equivalent to a* + b*?", c: "No, a* + b* only generates strings of pure a's or pure b's", o: ["No, a* + b* only generates strings of pure a's or pure b's", "Yes, they are identical", "No, (a+b)* cannot generate pure a's", "Yes, by distributive property"], d: 3, e: "(a+b)* generates 'ab', while a*+b* cannot.", k: "Star over Union" }
]);

// 4. top_re_building
genT('top_re_building', [
  { t: "Which Regular Expression represents all strings over {a,b} starting with 'a'?", c: "a(a+b)*", o: ["a(a+b)*", "(a+b)*a", "a* (a+b)*", "a(a+b)a"], d: 2, e: "Starts with 'a', followed by any string over {a,b}.", k: "Building REs" },
  { t: "Which Regular Expression represents all strings over {0,1} containing the substring '010'?", c: "(0+1)* 010 (0+1)*", o: ["(0+1)* 010 (0+1)*", "010 (0+1)*", "(0+1)* 010", "(0*1*0*)*"], d: 2, e: "Any prefix, the mandatory substring '010', and any suffix.", k: "Substring" },
  { t: "Write an RE for all strings over {0,1} that end in '11'.", c: "(0+1)* 11", o: ["(0+1)* 11", "11 (0+1)*", "(0+1)* 11 (0+1)*", "0* 11"], d: 2, e: "Any prefix followed by the mandatory suffix '11'.", k: "Suffix" },
  { t: "What is the RE for strings of even length over {a}?", c: "(aa)*", o: ["(aa)*", "a(aa)*", "a*a*", "(a)*"], d: 3, e: "Every iteration of the star adds exactly 2 'a's, ensuring the length is always even.", k: "Parity" },
  { t: "What is the RE for strings of odd length over {a}?", c: "a(aa)*", o: ["a(aa)*", "(aa)*", "a* (aa)*", "(aaa)*"], d: 3, e: "An even number of 'a's (aa)* plus exactly one more 'a' gives an odd length.", k: "Parity" },
  { t: "Which RE represents strings over {0,1} that contain exactly one '1'?", c: "0* 1 0*", o: ["0* 1 0*", "(0+1)* 1 (0+1)*", "0* 1", "1 0*"], d: 3, e: "Any number of 0s, exactly one 1, and any number of 0s. No other 1s are allowed.", k: "Exact count" },
  { t: "Which RE represents strings over {a,b} of length at most 2?", c: "ε + a + b + aa + ab + ba + bb", o: ["ε + a + b + aa + ab + ba + bb", "(a+b)(a+b)", "(a+b)*", "a*b*"], d: 3, e: "It explicitly lists all strings of length 0, 1, and 2. Alternatively, (ε+a+b)(ε+a+b).", k: "Bounded length" },
  { t: "Which RE represents the language of all strings over {0,1} that do NOT contain the substring '11'?", c: "(0 + 10)* (ε + 1)", o: ["(0 + 10)* (ε + 1)", "0* 1 0*", "(01)*", "(0+1)* 00 (0+1)*"], d: 5, e: "Every 1 must be immediately followed by a 0, except possibly at the very end of the string.", k: "Avoiding substring" },
  { t: "Which RE represents strings over {a,b} starting and ending with the same symbol (length >= 1)?", c: "a(a+b)*a + b(a+b)*b + a + b", o: ["a(a+b)*a + b(a+b)*b + a + b", "a(a+b)*a + b(a+b)*b", "(a+b)* a (a+b)*", "a(a+b)*b + b(a+b)*a"], d: 4, e: "Must include multi-character strings starting/ending with a or b, plus the single character strings 'a' and 'b'.", k: "Same start/end" },
  { t: "What does the RE (0+1)* 1 (0+1)* 1 (0+1)* represent?", c: "Strings containing at least two 1s", o: ["Strings containing at least two 1s", "Strings containing exactly two 1s", "Strings ending in 11", "Strings starting with 11"], d: 4, e: "It forces two 1s to appear, with any arbitrary prefix, middle, and suffix of 0s and 1s.", k: "At least constraint" }
]);

// 5. top_fa_and_re
genT('top_fa_and_re', [
  { t: "According to Kleene's Theorem, what is the relationship between FAs and REs?", c: "Every FA has an equivalent RE, and every RE has an equivalent FA", o: ["Every FA has an equivalent RE, and every RE has an equivalent FA", "FAs are more powerful than REs", "REs are more powerful than FAs", "They represent different classes of languages"], d: 2, e: "They are completely equivalent in expressive power.", k: "Kleene's Theorem" },
  { t: "Which algorithm converts a Regular Expression into an NFA with ε-transitions?", c: "Thompson's Construction", o: ["Thompson's Construction", "State Elimination", "Subset Construction", "Arden's Theorem"], d: 2, e: "Thompson's constructs an ε-NFA compositionally from the RE.", k: "Thompson's Construction" },
  { t: "Which algorithm converts a DFA into a Regular Expression?", c: "State Elimination Method", o: ["State Elimination Method", "Thompson's Construction", "Subset Construction", "Myhill-Nerode Theorem"], d: 2, e: "State Elimination and Arden's Theorem convert FAs to REs.", k: "DFA to RE" },
  { t: "When converting an FA to an RE, does the resulting RE depend on the order in which states are eliminated?", c: "The REs might look different but denote the same language", o: ["The REs might look different but denote the same language", "The exact same RE is always produced", "The language changes depending on the order", "It is impossible to eliminate states in different orders"], d: 3, e: "Different elimination orders yield algebraically equivalent, but potentially visually different, regular expressions.", k: "State Elimination Properties" },
  { t: "What is the primary significance of proving FAs and REs are equivalent?", c: "It unifies the procedural (FA) and declarative (RE) models of computation", o: ["It unifies the procedural (FA) and declarative (RE) models of computation", "It proves P = NP", "It shows Turing Machines are unnecessary", "It provides a way to minimize REs"], d: 3, e: "It shows that specifying a pattern (RE) is exactly as powerful as building a machine to parse it (FA).", k: "Significance of Equivalence" },
  { t: "In Thompson's construction, how many final states does the resulting ε-NFA have?", c: "Exactly one", o: ["Exactly one", "Multiple", "Zero", "Depends on the RE length"], d: 2, e: "Thompson's construction inherently builds sub-machines with exactly one start and one final state.", k: "Thompson's Properties" },
  { t: "If a language L is recognized by an NFA, can it be described by a Regular Expression?", c: "Yes, because NFAs are equivalent to DFAs, which are equivalent to REs", o: ["Yes, because NFAs are equivalent to DFAs, which are equivalent to REs", "No, NFAs are more powerful", "Only if it has no ε-transitions", "Only if the NFA is minimized"], d: 2, e: "NFA = DFA = RE. All describe Regular Languages.", k: "NFA to RE" },
  { t: "What is Arden's Theorem used for?", c: "Solving regular expression equations to convert FAs to REs", o: ["Solving regular expression equations to convert FAs to REs", "Converting REs to NFAs", "Minimizing DFAs", "Proving a language is not regular"], d: 3, e: "Arden's Theorem solves R = Q + RP to R = QP*, which is used when converting FAs to REs algebraically.", k: "Arden's Theorem" },
  { t: "Is the set of Regular Languages closed under conversion between REs and FAs?", c: "Yes, they define the exact same set", o: ["Yes, they define the exact same set", "No, converting to RE loses information", "No, FAs can express more", "Yes, but only for finite languages"], d: 1, e: "They are perfectly equivalent definitions of Regular Languages.", k: "Equivalence" },
  { t: "Can a non-regular language be described by a Regular Expression?", c: "No, REs only describe regular languages", o: ["No, REs only describe regular languages", "Yes, using the Kleene star", "Yes, if the expression is infinitely long", "No, unless it uses intersection"], d: 2, e: "By definition, REs describe exactly the regular languages.", k: "Limits of RE" }
]);

// 6. top_dfa_to_re
genT('top_dfa_to_re', [
  { t: "What is the general solution to the regular expression equation R = Q + RP, according to Arden's Theorem (assuming P does not contain ε)?", c: "R = QP*", o: ["R = QP*", "R = P*Q", "R = Q*P", "R = PQ*"], d: 3, e: "The recursion means R can be Q, QP, QPP, etc., which is exactly QP*.", k: "Arden's Theorem" },
  { t: "To apply Arden's theorem, what condition must hold for R = Q + RP?", c: "P must not contain the empty string ε", o: ["P must not contain the empty string ε", "Q must not contain ε", "R must be empty", "P and Q must be identical"], d: 4, e: "If P contains ε, the equation does not have a unique solution.", k: "Arden's Condition" },
  { t: "When setting up equations for a DFA to use Arden's Theorem, what does a variable like q_i represent?", c: "The regular expression for strings that take the DFA from state q_i to an accept state", o: ["The regular expression for strings that take the DFA from state q_i to an accept state", "The number of transitions into q_i", "The string that reaches q_i from the start state", "The empty string"], d: 4, e: "In the right-linear equation method, variables represent the language accepted starting from that state.", k: "Equation setup" },
  { t: "If a state q_i is a final state, what must be added to its equation?", c: "ε (the empty string)", o: ["ε (the empty string)", "∅ (the empty set)", "Σ (the alphabet)", "The start state"], d: 3, e: "Since q_i is final, accepting without reading any more symbols is possible, so ε is part of its language.", k: "Final state equation" },
  { t: "Given equations: q0 = a q1, q1 = b q1 + ε. What is the RE for q0?", c: "ab*", o: ["ab*", "a*b", "(ab)*", "a+b*"], d: 3, e: "From q1 = ε + b q1, Arden's gives q1 = εb* = b*. Substitute into q0: q0 = a(b*) = ab*.", k: "Solving equations" },
  { t: "Why is converting a DFA to an RE often more complex than converting an RE to an NFA?", c: "DFAs can have complex cycles and intersecting loops that require solving simultaneous equations", o: ["DFAs can have complex cycles and intersecting loops that require solving simultaneous equations", "DFAs have more states", "REs cannot represent infinite loops", "NFAs are deterministically equivalent"], d: 3, e: "Extracting an algebraic path from a heavily interconnected graph is combinatorially complex.", k: "Complexity" },
  { t: "In the equation approach, if q0 = a q0 + b q1 and q1 = ε, what is L(q0)?", c: "a*b", o: ["a*b", "a*+b", "(ab)*", "ab*"], d: 4, e: "Substitute q1: q0 = a q0 + b(ε) = b + a q0. By Arden's, q0 = ba* ... wait, R = Q + RP is left recursive. Standard is R = Q + PR => R=P*Q. Actually if q0 = a q0 + b, then R = b, P = a, so q0 = a*b. (Correct answer is a*b).", k: "Arden's Application" },
  { t: "What is the primary alternative to Arden's theorem for converting a DFA to an RE?", c: "State Elimination Method", o: ["State Elimination Method", "Subset Construction", "Hopcroft's Algorithm", "Thompson's Construction"], d: 2, e: "State elimination removes nodes from the graph visually, rather than solving equations algebraically.", k: "Alternatives" },
  { t: "If a DFA has no accept states, what is the resulting Regular Expression?", c: "∅", o: ["∅", "ε", "Σ*", "It depends on the start state"], d: 2, e: "No accept states means the DFA accepts nothing, which is the empty language ∅.", k: "Empty DFA" },
  { t: "What happens if you have an equation q = q?", c: "It has infinite solutions, and Arden's theorem cannot uniquely solve it", o: ["It has infinite solutions, and Arden's theorem cannot uniquely solve it", "q = ε", "q = ∅", "q = Σ*"], d: 4, e: "q = ∅ + q(ε). Since P contains ε, Arden's uniqueness condition fails.", k: "Arden's Failure" }
]);

// 7. top_state_elim
genT('top_state_elim', [
  { t: "In the State Elimination method, what is the first preparatory step?", c: "Add a new start state and a new final state with ε-transitions", o: ["Add a new start state and a new final state with ε-transitions", "Remove all dead states", "Minimize the DFA", "Convert all transitions to Kleene stars"], d: 2, e: "Adding isolated new start and final states ensures we don't accidentally sever paths when eliminating the original start/final states.", k: "Preparation" },
  { t: "When eliminating state q in a path p → q → r, what is the formula for the new direct edge p → r?", c: "(edge p→q) (loop q→q)* (edge q→r)", o: ["(edge p→q) (loop q→q)* (edge q→r)", "(edge p→q) + (edge q→r)", "(edge p→q) (edge q→r)*", "(edge p→r)*"], d: 3, e: "You must enter q, loop on q any number of times, and then exit q to r.", k: "Elimination Formula" },
  { t: "If there is no self-loop on the state q being eliminated, what does the loop term (q→q)* become in the formula?", c: "ε", o: ["ε", "∅", "It becomes invalid", "It remains as *"], d: 3, e: "If there is no loop, you loop 0 times, which is ε. The formula simplifies to (edge p→q)(edge q→r).", k: "No loop case" },
  { t: "If eliminating a state creates a new transition p → r, but an edge p → r already exists, what do you do?", c: "Label the edge with the Union (+) of the old label and the new label", o: ["Label the edge with the Union (+) of the old label and the new label", "Replace the old edge", "Keep the old edge and discard the new one", "State elimination fails in this case"], d: 3, e: "Parallel paths in an automaton represent a choice (Union/OR).", k: "Parallel Paths" },
  { t: "When do you stop eliminating states in the State Elimination method?", c: "When only the new start state and new final state remain", o: ["When only the new start state and new final state remain", "When all loops are removed", "When the DFA becomes an NFA", "When only one state is left"], d: 2, e: "The final single edge between the new start and new final state contains the complete regular expression.", k: "Termination" },
  { t: "What is the advantage of State Elimination over Arden's Theorem?", c: "It is often more visual and intuitive for small graphs", o: ["It is often more visual and intuitive for small graphs", "It always produces shorter expressions", "It avoids creating ε-transitions", "It can convert non-regular languages"], d: 3, e: "State elimination lets you visually bypass nodes, while Arden's requires rigorous algebraic substitution.", k: "Advantage" },
  { t: "Consider states 1, 2, 3. Edges: 1→2(a), 2→2(b), 2→3(c). Eliminating state 2 creates what edge from 1 to 3?", c: "ab*c", o: ["ab*c", "a+b*+c", "(abc)*", "a(b+c)*"], d: 3, e: "In via 'a', loop on 'b' any number of times, out via 'c'.", k: "Basic Elimination" },
  { t: "Why is it important to create a SINGLE new final state?", c: "So the final regular expression encapsulates all possible accepting paths in one expression", o: ["So the final regular expression encapsulates all possible accepting paths in one expression", "Because DFAs can only have one final state", "To make it deterministic", "To eliminate ε-transitions"], d: 3, e: "If there were multiple final states, you would have to calculate multiple expressions and union them at the end. A single new final state does this automatically.", k: "Single Final State" },
  { t: "Can the State Elimination method be applied to an NFA?", c: "Yes, it works directly on NFAs and DFAs", o: ["Yes, it works directly on NFAs and DFAs", "No, the automaton must be deterministic", "No, it only works on minimized DFAs", "Yes, but only if there are no ε-transitions"], d: 4, e: "The algorithm works by manipulating generalized transitions (which can be REs), so NFAs are perfectly fine.", k: "Applicability" },
  { t: "If state q has incoming edges from p1, p2 and outgoing to r1, r2, how many new edges are created when q is eliminated?", c: "4", o: ["4", "2", "0", "8"], d: 4, e: "You must connect every incoming node to every outgoing node: p1→r1, p1→r2, p2→r1, p2→r2.", k: "Combinatorial explosion" }
]);

// 8. top_re_to_fa
genT('top_re_to_fa', [
  { t: "Which algorithm structurally converts a Regular Expression into an ε-NFA?", c: "Thompson's Construction", o: ["Thompson's Construction", "State Elimination", "Subset Construction", "DFA Minimization"], d: 1, e: "Thompson's algorithm recursively builds an ε-NFA from an RE.", k: "Thompson's Algorithm" },
  { t: "In Thompson's Construction, what does the automaton for a single symbol 'a' look like?", c: "Two states connected by a transition labeled 'a'", o: ["Two states connected by a transition labeled 'a'", "One state with a self-loop labeled 'a'", "Three states with ε-transitions", "A single accept state"], d: 2, e: "The base case is simply a start state, a final state, and an edge 'a' between them.", k: "Base Case" },
  { t: "How is Union (R + S) constructed in Thompson's algorithm?", c: "A new start state with ε-transitions to the starts of R and S, and their finals connect via ε to a new final state", o: ["A new start state with ε-transitions to the starts of R and S, and their finals connect via ε to a new final state", "Merge the start states of R and S into one", "Connect the final of R to the start of S", "Add a self loop of R+S"], d: 3, e: "Branching with ε-transitions creates the 'OR' choice without consuming input.", k: "Union Construction" },
  { t: "How is Concatenation (RS) constructed in Thompson's algorithm?", c: "Merge the final state of R with the start state of S", o: ["Merge the final state of R with the start state of S", "Add an ε-transition from the start of R to the start of S", "Create a new start state pointing to both", "Connect the final of S to the start of R"], d: 2, e: "When R finishes successfully, it immediately feeds into the beginning of S.", k: "Concatenation Construction" },
  { t: "How many new states are introduced when applying the Kleene Star (R*) in Thompson's construction?", c: "2", o: ["2", "1", "0", "4"], d: 3, e: "A new start and a new final state are added to allow skipping R entirely and cleanly looping.", k: "Star Construction" },
  { t: "What is a guaranteed property of any ε-NFA generated by Thompson's construction?", c: "It has exactly one start state and one final state", o: ["It has exactly one start state and one final state", "It is deterministic", "It has no ε-transitions", "Every state is an accept state"], d: 3, e: "The construction rules mathematically preserve the invariant of exactly one start and one final state at every step.", k: "Thompson's Properties" },
  { t: "In Thompson's construction for R*, what prevents infinite ε-loops that consume no input?", c: "The construction structure ensures progress, though careless simulation can get stuck in ε-loops if not handled correctly", o: ["The construction structure ensures progress, though careless simulation can get stuck in ε-loops if not handled correctly", "It doesn't use ε-transitions", "R* is always deterministic", "The start state is removed"], d: 4, e: "The NFA contains ε-loops (e.g., new start -> old start -> old final -> new final? No, old final -> old start). Simulators must track ε-closures to avoid infinite loops.", k: "ε-loops" },
  { t: "To execute the resulting Thompson ε-NFA deterministically in software, what is typically done?", c: "Compute the ε-closure of states while processing characters", o: ["Compute the ε-closure of states while processing characters", "Run it backwards", "Eliminate states", "Use a stack"], d: 4, e: "This is essentially on-the-fly Subset Construction, used in regex engines like grep.", k: "Execution" },
  { t: "How many states will Thompson's construction produce for the RE 'a'?", c: "2", o: ["2", "1", "3", "4"], d: 2, e: "Start state, transition 'a', final state.", k: "State Counting" },
  { t: "Is the ε-NFA produced by Thompson's construction the smallest possible automaton for the RE?", c: "No, it often contains many redundant ε-transitions and states", o: ["No, it often contains many redundant ε-transitions and states", "Yes, it is minimal", "Yes, but only for finite languages", "No, but it is always a DFA"], d: 3, e: "It trades efficiency/minimality for structural simplicity and linear construction time.", k: "Minimality" }
]);

// 9. top_pump_rl
genT('top_pump_rl', [
  { t: "What is the primary purpose of the Pumping Lemma for Regular Languages?", c: "To prove that a specific language is NOT regular", o: ["To prove that a specific language is NOT regular", "To prove that a specific language IS regular", "To convert an NFA to a DFA", "To minimize a DFA"], d: 1, e: "It acts as a proof by contradiction tool for non-regularity.", k: "Purpose" },
  { t: "In the Pumping Lemma, s = xyz. What does the substring 'y' represent conceptually in the DFA?", c: "A cycle or loop of states", o: ["A cycle or loop of states", "The start state", "The accept states", "The empty string"], d: 2, e: "Since the DFA has finite states, a long enough string must revisit a state, creating a loop (y).", k: "Concept of y" },
  { t: "What is the condition on the length of y in the Pumping Lemma?", c: "|y| > 0", o: ["|y| > 0", "|y| >= 0", "|y| = p", "|y| < p"], d: 2, e: "The loop must consume at least one character, otherwise pumping it does nothing.", k: "Condition 1" },
  { t: "What is the condition on the length of xy in the Pumping Lemma?", c: "|xy| <= p", o: ["|xy| <= p", "|xy| > p", "|xy| = 0", "|xy| >= p"], d: 3, e: "The first repetition of a state must occur within the first p characters (Pigeonhole Principle).", k: "Condition 2" },
  { t: "What does 'pumping' mean in the context of the lemma?", c: "Repeating the substring y any number of times (i >= 0) and checking if the result is still in the language", o: ["Repeating the substring y any number of times (i >= 0) and checking if the result is still in the language", "Removing characters from x and z", "Reversing the string", "Increasing the number of states"], d: 2, e: "x(y^i)z ∈ L for all i ≥ 0.", k: "Pumping" },
  { t: "Can you use the Pumping Lemma to prove a language IS regular?", c: "No, satisfying the Pumping Lemma is a necessary but not sufficient condition for regularity", o: ["No, satisfying the Pumping Lemma is a necessary but not sufficient condition for regularity", "Yes, by showing it can be pumped", "Yes, if p is large enough", "No, it is only used for Context-Free Languages"], d: 4, e: "There exist non-regular languages that satisfy the Pumping Lemma conditions.", k: "Necessary vs Sufficient" },
  { t: "What mathematical principle underlies the Pumping Lemma?", c: "The Pigeonhole Principle", o: ["The Pigeonhole Principle", "Mathematical Induction", "De Morgan's Laws", "The Halting Problem"], d: 2, e: "If a string is longer than the number of states, it must 'pigeonhole' at least two characters into the same state.", k: "Pigeonhole Principle" },
  { t: "If you pump with i=0 (i.e., xy^0z = xz), what are you conceptually doing?", c: "Bypassing the loop in the DFA", o: ["Bypassing the loop in the DFA", "Getting stuck in an infinite loop", "Going to a dead state", "Rejecting the string"], d: 3, e: "Since y is the loop, pumping 0 times means you traverse the path without taking the loop.", k: "Pumping Down" },
  { t: "In a formal proof using the Pumping Lemma, who chooses the string 's'?", c: "You (the prover), but it must belong to L and |s| >= p", o: ["You (the prover), but it must belong to L and |s| >= p", "The adversary", "It is fixed as a^p b^p", "It must be empty"], d: 4, e: "You choose s strategically to force a contradiction, usually locking the loop 'y' into a specific part of the string.", k: "Proof Mechanics" },
  { t: "In a formal proof, who chooses the decomposition of s into xyz?", c: "The adversary (you must account for all possible valid decompositions)", o: ["The adversary (you must account for all possible valid decompositions)", "You (the prover)", "It is always x=ε, y=s, z=ε", "The pumping lemma algorithm"], d: 4, e: "You cannot assume y is a specific substring. You must prove it breaks FOR ALL possible y's that satisfy |xy|<=p and |y|>0.", k: "Proof Mechanics" }
]);

// 10. top_pump_rl_apps
genT('top_pump_rl_apps', [
  { t: "When proving L = {a^n b^n | n >= 0} is not regular, what is the best choice for the string s?", c: "s = a^p b^p", o: ["s = a^p b^p", "s = a b", "s = a^n b^n", "s = a^p"], d: 3, e: "Choosing a^p b^p ensures the first p characters are all 'a's, forcing the loop 'y' to consist entirely of 'a's.", k: "Strategic Choice of s" },
  { t: "For L = {a^n b^n}, if s = a^p b^p, what must the substring 'y' consist of?", c: "Only 'a's", o: ["Only 'a's", "Only 'b's", "A mix of 'a's and 'b's", "The empty string"], d: 3, e: "Because |xy| <= p, and the first p characters of s are 'a's, y must fall entirely within the 'a's.", k: "Forcing y" },
  { t: "After determining y is only 'a's for L = {a^n b^n}, what happens when you pump with i=2?", c: "The string gains more 'a's but the number of 'b's stays the same, so it's not in L", o: ["The string gains more 'a's but the number of 'b's stays the same, so it's not in L", "The string gains more 'b's", "The string remains in L", "The string becomes empty"], d: 2, e: "This breaks the n=n condition, yielding a contradiction.", k: "The Contradiction" },
  { t: "Can a DFA count an unbounded number of items?", c: "No, because it has finite memory (states)", o: ["No, because it has finite memory (states)", "Yes, using loops", "Yes, if the alphabet is binary", "No, but an NFA can"], d: 2, e: "Finite Automata cannot match unbounded paired structures (like a^n b^n) because they run out of states to count n.", k: "Unbounded Counting" },
  { t: "Prove L = {a^p | p is a prime number} is not regular. If you pump y (length k) i times, what i is a strategic choice to force a non-prime length?", c: "i = |xz| + 1", o: ["i = |xz| + 1", "i = 2", "i = 0", "i = p"], d: 5, e: "Length becomes |xz| + i|y| = |xz| + (|xz|+1)k = |xz|(1+k) + k. (Actually, i = |xz| + 1 gives length |xz| + |xz|k + k = (|xz|+k)(1) wait, standard is i = |xz|+1 wait no, if s is length p, length after pumping is p + (i-1)|y|. If i = p+1, length is p + p|y| = p(1+|y|), which is composite.)", k: "Prime Lengths" },
  { t: "Which of the following languages is REGULAR and cannot be proven non-regular with the Pumping Lemma?", c: "Strings with an even number of a's", o: ["Strings with an even number of a's", "Palindromes", "Strings with equal a's and b's", "Properly nested parentheses"], d: 2, e: "Even 'a's only requires modulo 2 counting (2 states). The others require unbounded counting.", k: "Regular vs Non-Regular" },
  { t: "When pumping L = {ww | w is a string over {a,b}}, what is a strong adversarial choice for s?", c: "s = a^p b a^p b", o: ["s = a^p b a^p b", "s = a^p a^p", "s = a b a b", "s = w w"], d: 5, e: "a^p b a^p b forces y to be entirely 'a's in the first half. Pumping it imbalances the two halves.", k: "Choice of s" },
  { t: "What is the logical consequence if a language L fails the Pumping Lemma?", c: "L is definitely not a regular language", o: ["L is definitely not a regular language", "L is definitely regular", "The test is inconclusive", "L must be a context-free language"], d: 2, e: "Modus tollens: Regular => Pumps. Fails to Pump => Not Regular.", k: "Logical Consequence" },
  { t: "Why doesn't s = a^(p/2) b^(p/2) work for proving L = {a^n b^n} is non-regular?", c: "Because |xy| <= p might allow y to cross the a/b boundary, complicating the proof", o: ["Because |xy| <= p might allow y to cross the a/b boundary, complicating the proof", "Because p might be odd", "Because it is already in L", "It does work perfectly"], d: 4, e: "If y spans a's and b's, pumping y creates out-of-order characters (e.g., abab), which is still not in L, but restricting y to purely 'a's (by using a^p b^p) is an easier proof.", k: "Proof Strategy" },
  { t: "If you pump down (i=0) and the resulting string is not in L, what have you achieved?", c: "You have found a contradiction and proved L is not regular", o: ["You have found a contradiction and proved L is not regular", "You must try i=2 instead", "You chose the wrong string s", "The language is regular"], d: 3, e: "Finding ANY i >= 0 that produces a string outside L is sufficient for the contradiction.", k: "Pumping Down" }
]);

// 11. top_closure_rl
genT('top_closure_rl', [
  { t: "What does it mean for Regular Languages to be 'closed' under Union?", c: "If L1 and L2 are regular, L1 U L2 is guaranteed to be regular", o: ["If L1 and L2 are regular, L1 U L2 is guaranteed to be regular", "L1 U L2 is always finite", "The DFA for L1 U L2 is closed (no dead states)", "Union removes non-regular strings"], d: 1, e: "Closure means the operation preserves the property of being a Regular Language.", k: "Definition of Closure" },
  { t: "Are Regular Languages closed under Intersection?", c: "Yes", o: ["Yes", "No", "Only if the alphabets are identical", "Only for finite languages"], d: 1, e: "Proved via the Cartesian Product machine construction or De Morgan's laws.", k: "Intersection Closure" },
  { t: "How do you construct a DFA for the Complement of a Regular Language L?", c: "Take the DFA for L and swap the accept and non-accept states", o: ["Take the DFA for L and swap the accept and non-accept states", "Reverse all the arrows", "Change the start state to an accept state", "You cannot, it might not be regular"], d: 2, e: "Since a DFA deterministically consumes the entire string and halts in exactly one state, swapping final/non-final states perfectly flips acceptance.", k: "Complement Construction" },
  { t: "If L1 is regular and L2 is non-regular, what can be said about L1 ∩ L2?", c: "It could be regular or non-regular", o: ["It could be regular or non-regular", "It is always non-regular", "It is always regular", "It is empty"], d: 4, e: "Example: L1=∅ (regular), L1 ∩ L2 = ∅ (regular). L1=Σ* (regular), L1 ∩ L2 = L2 (non-regular).", k: "Mixed Operations" },
  { t: "Are Regular Languages closed under Subset?", c: "No", o: ["No", "Yes", "Only for infinite languages", "Yes, every subset of a regular language is regular"], d: 3, e: "Σ* is regular. {a^n b^n} is a subset of Σ*, but is NOT regular.", k: "Subset Non-Closure" },
  { t: "Which operation is used to prove Closure under Reversal (L^R)?", c: "Take the FA, make the start state final, final states start, and reverse all transition arrows", o: ["Take the FA, make the start state final, final states start, and reverse all transition arrows", "Reverse the Regular Expression string", "Swap accept and reject states", "Cartesian product"], d: 3, e: "Reversing the arrows creates an NFA that accepts strings from back to front.", k: "Reversal Construction" },
  { t: "If L is regular, is the language consisting of all prefixes of strings in L regular?", c: "Yes", o: ["Yes", "No", "Only if L is finite", "It depends on the alphabet"], d: 4, e: "Make every state that is on a path to a final state an accept state.", k: "Prefix Closure" },
  { t: "How is Closure under Intersection useful in proofs?", c: "It can prove a language is non-regular by intersecting a suspected language with a known regular one", o: ["It can prove a language is non-regular by intersecting a suspected language with a known regular one", "It minimizes DFAs", "It generates Regular Expressions", "It removes ε-transitions"], d: 4, e: "If L(unknown) ∩ L(regular) = L(non-regular), then L(unknown) MUST be non-regular. (If it were regular, the intersection would be regular).", k: "Proof Technique" },
  { t: "Are Regular Languages closed under Set Difference (L1 - L2)?", c: "Yes, because L1 - L2 = L1 ∩ (Complement of L2)", o: ["Yes, because L1 - L2 = L1 ∩ (Complement of L2)", "No, subtraction breaks regularity", "Yes, but only if L1 is a subset of L2", "No, unless they are finite"], d: 3, e: "Since RLs are closed under complement and intersection, they must be closed under difference.", k: "Set Difference" },
  { t: "Which of the following is NOT a closure property of Regular Languages?", c: "Closure under Infinite Union", o: ["Closure under Infinite Union", "Closure under Finite Union", "Closure under Kleene Star", "Closure under Homomorphism"], d: 4, e: "RLs are closed under FINITE union. Infinite union can create non-regular languages (e.g., Union of {a^n b^n} for all n yields a non-regular set).", k: "Infinite Union" }
]);

// 12. top_decision_rl
genT('top_decision_rl', [
  { t: "What does the Emptiness Problem for a Regular Language ask?", c: "Is the language accepted by the DFA empty (L = ∅)?", o: ["Is the language accepted by the DFA empty (L = ∅)?", "Does the DFA have zero states?", "Does the string contain the empty string ε?", "Is the alphabet empty?"], d: 1, e: "It asks whether there exists ANY string that the machine accepts.", k: "Emptiness Problem" },
  { t: "How do you algorithmically decide the Emptiness Problem for a DFA?", c: "Run a graph traversal (BFS/DFS) from the start state to see if any accept state is reachable", o: ["Run a graph traversal (BFS/DFS) from the start state to see if any accept state is reachable", "Check if the start state is an accept state", "Check if it has any loops", "Simulate all possible strings"], d: 2, e: "If no accept state is reachable in the graph, the language is empty.", k: "Emptiness Algorithm" },
  { t: "What does the Finiteness Problem ask?", c: "Does the DFA accept a finite number of strings?", o: ["Does the DFA accept a finite number of strings?", "Does the DFA have a finite number of states?", "Is the string length finite?", "Is the alphabet finite?"], d: 1, e: "It asks whether L(M) is a finite or infinite set.", k: "Finiteness Problem" },
  { t: "How do you decide the Finiteness Problem for a DFA?", c: "Check if there is a reachable cycle on a path to an accept state", o: ["Check if there is a reachable cycle on a path to an accept state", "Check if there are any accept states", "Check if the start state has a self-loop", "Count the number of states"], d: 3, e: "If there is a cycle that can reach a final state, you can pump it infinitely, meaning L is infinite. If no such cycle exists, L is finite.", k: "Finiteness Algorithm" },
  { t: "What is the Membership Problem?", c: "Given a string w and a DFA M, is w ∈ L(M)?", o: ["Given a string w and a DFA M, is w ∈ L(M)?", "Given a state q, is it a member of F?", "Is L1 a subset of L2?", "Is the alphabet a member of the language?"], d: 1, e: "It just asks if a specific string is accepted by the machine.", k: "Membership Problem" },
  { t: "How is the Equivalence Problem (L(M1) = L(M2)) algorithmically decided?", c: "Construct a DFA for the Symmetric Difference and test it for emptiness", o: ["Construct a DFA for the Symmetric Difference and test it for emptiness", "Check if M1 and M2 have the same number of states", "Test them with infinite strings", "Minimize both DFAs and check if they have the same start state"], d: 3, e: "Symmetric Difference = (L1 ∩ L2') U (L1' ∩ L2). If this is empty, L1 = L2.", k: "Equivalence Algorithm" },
  { t: "Alternatively, how can Equivalence be tested using DFA Minimization?", c: "Minimize both DFAs and check if the resulting graphs are identical (isomorphic)", o: ["Minimize both DFAs and check if the resulting graphs are identical (isomorphic)", "Minimize one and see if it equals the other", "Check if they minimize to a single state", "Minimization cannot test equivalence"], d: 3, e: "The minimal DFA for a regular language is unique up to state renaming. So two equivalent DFAs will yield the same minimal DFA.", k: "Equivalence via Minimization" },
  { t: "Are all decision problems for Regular Languages decidable?", c: "Yes, membership, emptiness, finiteness, and equivalence are all decidable", o: ["Yes, membership, emptiness, finiteness, and equivalence are all decidable", "No, equivalence is undecidable", "No, finiteness is undecidable", "Yes, except the halting problem for DFAs"], d: 3, e: "Because DFAs are strictly bounded, finite graphs, we can always answer these questions in finite time.", k: "Decidability" },
  { t: "What is the time complexity of the Membership Problem for a DFA?", c: "O(|w|), where |w| is the length of the string", o: ["O(|w|), where |w| is the length of the string", "O(N) where N is the number of states", "O(2^|w|)", "O(1)"], d: 2, e: "You process exactly one transition per character in the string. It takes linear time relative to string length.", k: "Time Complexity" },
  { t: "If a DFA has N states, what string lengths need to be tested to decide Emptiness (without a graph algorithm)?", c: "All strings of length less than N", o: ["All strings of length less than N", "All strings of length N or more", "Only the empty string", "Strings up to length 2N"], d: 4, e: "If it accepts anything, it must accept a string without loops (length < N). Testing all such strings decides emptiness.", k: "Emptiness Bound" }
]);

const content = `import { Question } from '../../types';\n\nexport const MODULE_2_QUESTIONS: Question[] = [\n${questions.join(',\n')}\n];\n`;
fs.writeFileSync('src/lib/content/questions2.ts', content);
